Repository department-of-veterans-affairs/component-library, pull requests merged in 2021-11, with the labels that each got.

#218 Only export applyPolyfills from the loader
  packages/core/package.json
  packages/core/src/main.js
  packages/web-components/package.json
  yarn.lock
Labels: fix

#210 Update README.md with publishing instructions
  README.md
Labels: documentation

#207 Add loading indicator web component
  packages/core/package.json
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.jsx
  packages/storybook/stories/LoadingIndicator.stories.jsx
  packages/storybook/stories/va-loading-indicator.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-loading-indicator/test/va-loading-indicator.e2e.ts
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.css
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
Labels: enhancement

#222 Add initial release notes config file
  .github/release.yml
Labels: documentation

#223 Isolate host styling in "Back to top"
  packages/core/package.json
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-back-to-top/test/va-back-to-top.e2e.ts
  packages/web-components/src/components/va-back-to-top/va-back-to-top.css
  packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx
Labels: fix

#226 32229 accordion header api slot
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/src/components/va-accordion/va-accordion-item.css
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/utils/utils.ts
Labels: enhancement, test

#228 Auto-expand va-accordion-item with matching hash
  packages/core/package.json
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: enhancement
