Repository department-of-veterans-affairs/component-library, pull requests merged in 2021-12, with the labels that each got.

#229 Add option to show icon in background-only alert for <va-alert>
  packages/core/package.json
  packages/storybook/stories/va-alert.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/va-alert.css
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: enhancement

#237 Increase minor version of core & web-components to 3.8
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#230 32860 Segmented Progress Bar Web Component
  packages/storybook/stories/va-segmented-progress-bar.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.css
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: enhancement

#245 34239 Segmented Progress Bar WC Aria Label displays incorrect default text
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: bug

#247 Fix web components/storybook in IE11
  packages/core/package.json
  packages/core/webpack.config.js
  packages/storybook/.storybook/main.js
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: fix
