Repository department-of-veterans-affairs/component-library, pull requests merged in 2021-02, with the labels that each got.

#26 Show out of range year error messages
  package.json
  src/components/Date/Date.jsx
  src/components/Date/Date.unit.spec.jsx
  src/components/MonthYear/MonthYear.jsx
  src/components/MonthYear/MonthYear.unit.spec.jsx
  src/helpers/validations.js
Labels: severity 1 critical

#25 Select 508 enchancement
  package.json
  src/components/Select/Select.jsx
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.jsx
  src/components/Select/Select.unit.spec.jsx
Labels: documentation, enhancement

#16 Wrap Date in a fieldset
  package.json
  src/components/Date/Date.jsx
  src/components/Date/Date.unit.spec.jsx
  src/components/MonthYear/MonthYear.jsx
  src/components/MonthYear/MonthYear.unit.spec.jsx
Labels: enhancement

#34 Add error class to Date fieldset
  src/components/Date/Date.jsx
Labels: bug

#36 Update to 3-digit telephone numbers
  package.json
  src/components/Telephone/Telephone.jsx
  src/components/Telephone/Telephone.mdx
  src/components/Telephone/Telephone.unit.spec.jsx
Labels: bug, severity 1 critical
