Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-10, with the labels that each got.

#543 Updating va-button Storybook example to React binding
  packages/storybook/stories/va-radio.stories.jsx
Labels: ignore-for-release

#544 Update va-privacy-agreement maturity and location in Storybook.
  packages/storybook/stories/PrivacyAgreement.stories.jsx
  packages/storybook/stories/va-privacy-agreement.stories.jsx
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.tsx
Labels: ignore-for-release

#552 Skipping flakey shadowRoot tests in va-privacy-agreement
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
Labels: ignore-for-release

#545 Remove RadioButtons React component from Storybook.
  packages/storybook/stories/RadioButtons.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: ignore-for-release

#550 Remove PrivacyAgreement React component
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/src/components/PrivacyAgreement/PrivacyAgreement.jsx
  packages/react-components/src/components/PrivacyAgreement/PrivacyAgreement.mdx
  packages/react-components/src/components/PrivacyAgreement/PrivacyAgreement.unit.spec.jsx
  packages/react-components/src/index.js
  packages/web-components/package.json
Labels: major

#547 Remove HelpMenu React component
  packages/react-components/index.js
  packages/react-components/src/components/HelpMenu/HelpMenu.jsx
  packages/react-components/src/components/HelpMenu/HelpMenu.mdx
  packages/react-components/src/components/HelpMenu/HelpMenu.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/HelpMenu.stories.jsx
  packages/storybook/stories/additional-docs.js
  packages/web-components/package.json
Labels: major

#549 Remove AcceptTerms React component
  packages/react-components/index.js
  packages/react-components/src/components/AcceptTermsPrompt/AcceptTermsPrompt.jsx
  packages/react-components/src/components/AcceptTermsPrompt/AcceptTermsPrompt.mdx
  packages/react-components/src/components/AcceptTermsPrompt/AcceptTermsPrompt.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/AcceptTermsPrompt.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#548 Remove IconHelp React component
  packages/react-components/index.js
  packages/react-components/src/components/IconHelp/IconHelp.jsx
  packages/react-components/src/components/IconHelp/IconHelp.mdx
  packages/react-components/src/components/IconHelp/IconHelp.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/IconHelp.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#555 va-alert background-only layout issue
  packages/web-components/src/components/va-alert/va-alert.css
Labels: minor

#535 Add radio hint prop & tweak aria label
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.css
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: bug, enhancement, minor
