Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-05, with the labels that each got.

#354 Add typeahead functionality to va-search-input
  packages/core/package.json
  packages/storybook/stories/va-search-input.stories.jsx
  packages/storybook/stories/va-search.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.css
  packages/web-components/src/components/va-search-input/va-search-input.tsx
  packages/web-components/src/components/va-search/test/va-search.e2e.ts
  packages/web-components/src/components/va-search/va-search.tsx
  packages/web-components/src/mixins/focusable.css
Labels: minor

#403 40575 va-date convert to use va-text-input for year field
  packages/core/package.json
  packages/storybook/stories/va-date.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.css
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.css
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#401 Add subtitle and link to DS for va-progress-bar and va-segmented-progress-bar
  packages/storybook/stories/va-progress-bar.stories.jsx
  packages/storybook/stories/va-segmented-progress-bar.stories.jsx
Labels: ignore-for-release

#405 Add subtitle and link to DS for va-process-list
  packages/storybook/stories/va-process-list.stories.jsx
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#393 Update success status for va-text-input
  packages/core/package.json
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.css
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: major

#410 Fix va-segmented-progress-bar link to DS
  packages/storybook/stories/va-segmented-progress-bar.stories.jsx
Labels: ignore-for-release

#404 Add va-alert-expandable component
  packages/storybook/stories/va-alert-expandable.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
  packages/web-components/src/global/variables.css
Labels: minor

#415 773 Fix Form Control links from Storybook to design.va
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/storybook/stories/va-date.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
Labels: ignore-for-release

#416 Add initial translation values
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
Labels: minor

#367 Translate accordion
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: minor

#394 Translate date React component
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/react-components/src/components/Date/Date.jsx
  packages/react-components/src/components/Date/Date.unit.spec.jsx
  packages/react-components/src/components/Date/SimpleDate.jsx
  packages/react-components/src/components/Date/SimpleDate.unit.spec.jsx
  packages/react-components/src/helpers/options-for-select.js
  packages/storybook/stories/Date.stories.jsx
Labels: minor

#414 39872 va-alert storybook story name updates
  packages/storybook/stories/va-alert.stories.jsx
Labels: ignore-for-release

#376 Internationalize the number input component
  packages/react-components/src/components/NumberInput/NumberInput.jsx
  packages/react-components/src/components/NumberInput/NumberInput.unit.spec.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: minor

#389 Add i18next to Select and va-select
  packages/react-components/src/components/Select/Select.jsx
  packages/react-components/src/components/Select/Select.unit.spec.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/web-components/src/components/va-select/va-select.tsx
Labels: minor

#420 Translate text input
  packages/react-components/src/components/TextInput/TextInput.jsx
  packages/react-components/src/components/TextInput/TextInput.unit.spec.jsx
  packages/storybook/stories/TextInput.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#421 Bump version publishing translation changes
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#422 Bump react-components version
  packages/core/package.json
  packages/react-components/package.json
Labels: ignore-for-release

#423 Fix react build public path
  packages/core/package.json
  packages/core/src/i18n/translations/es.js
  packages/core/webpack.config.js
  packages/react-components/package.json
  packages/web-components/package.json
Labels: patch

#419 Update stories for Button
  packages/storybook/stories/ProgressButton.stories.jsx
  packages/storybook/stories/buttons.stories.mdx
  packages/storybook/stories/buttons.style.scss
Labels: ignore-for-release

#418 fix: updating tabindex to -1 to stop keyboard nav
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: patch

#428 Focus only radio button for va-radio
  packages/web-components/src/components/va-radio-option/va-radio-option.css
Labels: minor

#417 Add textarea web component
  packages/core/package.json
  packages/storybook/stories/va-textarea.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.css
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/mixins/focusable.css
Labels: minor

#431 791 Storybook Dismissable Background
  packages/storybook/stories/va-alert.stories.jsx
Labels: ignore-for-release

#427 40076 aria describedby remove from va-text-input
  packages/core/package.json
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#429 Update padding and border width for va-alert
  packages/storybook/stories/va-alert.stories.jsx
  packages/web-components/src/components/va-alert/va-alert.css
Labels: minor

#435 Add subtitle and link to DS for va-featured-content
  packages/storybook/stories/va-featured-content.stories.jsx
Labels: ignore-for-release

#436 38913 Storybook Native Events in Docs
  packages/storybook/stories/events.js
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/storybook/stories/va-textarea.stories.jsx
Labels: ignore-for-release

#437 Add maturity scale to Storybook
  packages/storybook/.storybook/manager.js
  packages/storybook/stories/Breadcrumbs.stories.jsx
  packages/storybook/stories/Checkbox.stories.jsx
  packages/storybook/stories/Date.stories.jsx
  packages/storybook/stories/MaintenanceBanner.stories.jsx
  packages/storybook/stories/Modal.stories.jsx
  packages/storybook/stories/NumberInput.stories.jsx
  packages/storybook/stories/OMBInfo.stories.jsx
  packages/storybook/stories/Pagination.stories.jsx
  packages/storybook/stories/ProgressButton.stories.jsx
  packages/storybook/stories/RadioButtons.stories.jsx
  packages/storybook/stories/Select.stories.jsx
  packages/storybook/stories/Table.stories.jsx
  packages/storybook/stories/TextArea.stories.jsx
  packages/storybook/stories/TextInput.stories.jsx
  packages/storybook/stories/action-link.stories.mdx
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/address-block.stories.mdx
  packages/storybook/stories/buttons.stories.mdx
  packages/storybook/stories/divider.stories.mdx
  packages/storybook/stories/events.js
  packages/storybook/stories/horizontal-rules.stories.mdx
  packages/storybook/stories/labels.stories.mdx
  packages/storybook/stories/maturity-scale.js
  packages/storybook/stories/sidenav.stories.mdx
  packages/storybook/stories/tag.stories.mdx
  packages/storybook/stories/va-accordion.stories.jsx
  packages/storybook/stories/va-additional-info.stories.jsx
  packages/storybook/stories/va-alert-expandable.stories.jsx
  packages/storybook/stories/va-alert.stories.jsx
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/storybook/stories/va-banner.stories.jsx
  packages/storybook/stories/va-breadcrumbs.stories.jsx
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/storybook/stories/va-date.stories.jsx
  packages/storybook/stories/va-featured-content.stories.jsx
  packages/storybook/stories/va-loading-indicator.stories.jsx
  packages/storybook/stories/va-modal.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/storybook/stories/va-on-this-page.stories.jsx
  packages/storybook/stories/va-pagination.stories.jsx
  packages/storybook/stories/va-process-list.stories.jsx
  packages/storybook/stories/va-progress-bar.stories.jsx
  packages/storybook/stories/va-promo-banner.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/storybook/stories/va-search-input.stories.jsx
  packages/storybook/stories/va-segmented-progress-bar.stories.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/storybook/stories/va-table.stories.jsx
  packages/storybook/stories/va-telephone.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/storybook/stories/va-textarea.stories.jsx
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#446 Update usage report regex for bindings import
  packages/design-system-dashboard-cli/src/find-ds-components.js
Labels: ignore-for-release
