Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-09, with the labels that each got.

#518 Fix alert expandable component calc-max-height
  packages/core/package.json
  packages/storybook/.storybook/style.scss
  packages/storybook/stories/va-alert-expandable.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
Labels: minor

#515 Add grid utilities
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/tokens/flex-grid.scss
  packages/css-library/src/utilities/_index.scss
  packages/css-library/src/utilities/flex-grid.scss
  packages/css-library/src/utilities/float-grid.scss
  packages/css-library/src/utilities/settings.scss
Labels: ignore-for-release

#526 Add translation custom doc tags
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#525 Update publishing instructions
  README.md
  packages/core/README.md
Labels: ignore-for-release

#502 40212 remove react date
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Date/Date.jsx
  packages/react-components/src/components/Date/Date.mdx
  packages/react-components/src/components/Date/Date.unit.spec.jsx
  packages/react-components/src/components/Date/SimpleDate.jsx
  packages/react-components/src/components/Date/SimpleDate.unit.spec.jsx
  packages/react-components/src/helpers/validations.js
  packages/react-components/src/index.js
  packages/storybook/stories/Date.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#527 Remove MonthYear React component
  packages/react-components/index.js
  packages/react-components/src/components/MonthYear/MonthYear.jsx
  packages/react-components/src/components/MonthYear/MonthYear.mdx
  packages/react-components/src/components/MonthYear/MonthYear.unit.spec.jsx
  packages/react-components/src/helpers/options-for-select.js
  packages/react-components/src/helpers/validations.js
  packages/react-components/src/index.js
  packages/storybook/stories/MonthYear.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#528 Remove NumberInput React component
  packages/react-components/index.js
  packages/react-components/src/components/NumberInput/NumberInput.jsx
  packages/react-components/src/components/NumberInput/NumberInput.mdx
  packages/react-components/src/components/NumberInput/NumberInput.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/NumberInput.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#530 Fix va-checkbox label alignment.
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/va-checkbox.css
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#531 add id to featured content story
  packages/storybook/stories/va-featured-content.stories.jsx
Labels: ignore-for-release

#534 Add label prop value to va-button in the va-file-input component
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#533 Fix month validation
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#532 Align web component labels, descriptions, and error message font weights.
  packages/web-components/src/components/va-checkbox/va-checkbox.css
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/mixins/form-field-error.css
Labels: patch

#536 Moving file input web component and React component in Storybook sidebar
  packages/storybook/stories/FileInput.stories.jsx
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-file-input.stories.jsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#537 Move margin from error-message to label in va-checkbox.
  packages/web-components/src/components/va-checkbox/va-checkbox.css
Labels: patch

#538 Adding waitForChanges to va-privacy-agreement tests
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
Labels: patch

#541 Fix font family for input elements
  packages/web-components/src/components/va-select/va-select.css
  packages/web-components/src/components/va-text-input/va-text-input.css
Labels: patch
