Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-01, with the labels that each got.

#258 Fix NumberInput styling
  packages/core/package.json
  packages/react-components/package.json
  packages/react-components/src/components/NumberInput/NumberInput.jsx
  packages/react-components/src/components/NumberInput/NumberInput.unit.spec.jsx
Labels: fix

#256 Change modal header to h1
  packages/react-components/src/components/Modal/Modal.jsx
  packages/react-components/src/components/Modal/Modal.unit.spec.jsx
  packages/storybook/stories/Modal.stories.jsx
Labels: fix

#259 Update OMBInfo property description
  packages/react-components/src/components/OMBInfo/OMBInfo.jsx
  packages/react-components/src/components/OMBInfo/OMBInfo.mdx
  packages/storybook/stories/OMBInfo.stories.jsx
Labels: fix

#262 Add prop for res burden feature name
  packages/react-components/src/components/OMBInfo/OMBInfo.jsx
  packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
  packages/storybook/stories/OMBInfo.stories.jsx
Labels: enhancement

#263 BREAKING CHANGE: removed REACT progress bar and segmented progress bar
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/ProgressBar/ProgressBar.jsx
  packages/react-components/src/components/ProgressBar/ProgressBar.mdx
  packages/react-components/src/components/ProgressBar/ProgressBar.unit.spec.jsx
  packages/react-components/src/components/SegmentedProgressBar/SegmentedProgressBar.jsx
  packages/react-components/src/components/SegmentedProgressBar/SegmentedProgressBar.mdx
  packages/react-components/src/components/SegmentedProgressBar/SegmentedProgressBar.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/ProgressBar.stories.jsx
  packages/storybook/stories/SegmentedProgressBar.stories.jsx
Labels: breaking

#254 Fix core bundling for IE 11
  packages/core/package.json
  packages/core/src/main.js
  packages/web-components/package.json
Labels: fix

#267 Update va-accordion-item paragraphs to wrap
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.css
Labels: fix

#264 Fix Pagination keyboard navigation
  packages/core/package.json
  packages/react-components/package.json
  packages/react-components/src/components/Pagination/Pagination.jsx
  packages/react-components/src/components/Pagination/Pagination.unit.spec.jsx
Labels: fix

#274 Require label on PRs
  .github/workflows/require-label.yml
Labels: ignore-for-release

#273 27940 va-text-input WC Max Char Aria Accessibility
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#272 34439 Remove date-fns dependency from component library
  packages/core/package.json
  packages/storybook/package.json
  packages/storybook/stories/MaintenanceBanner.stories.jsx
  yarn.lock
Labels: patch
