Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-12, with the labels that each got.

#585 va-textarea: Add a11y css import and font styles.
  packages/web-components/package.json
  packages/web-components/src/components/va-textarea/va-textarea.css
Labels: patch

#584 Remove left padding and adjust option spacing in va-radio and va-radio-option
  packages/web-components/src/components/va-radio-option/va-radio-option.css
  packages/web-components/src/components/va-radio/va-radio.css
Labels: patch

#583 Add add to calendar variation to va-link
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.css
  packages/web-components/src/components/va-link/va-link.tsx
Labels: minor

#579 Add va-radio USWDS v3 version
  packages/core/package.json
  packages/storybook/.storybook/preview.js
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.css
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/mixins/inputs.css
  packages/web-components/src/mixins/uswds-error-border.css
  packages/web-components/src/utils/utils.ts
  packages/web-components/stencil.config.ts
  yarn.lock
Labels: minor

#513 Add analytics details for web components
  packages/storybook/stories/va-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: patch

#588 va-radio: add part attr to all elements
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: enhancement, minor

#589 Bug: Increase z-index in vaModel component
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.css
Labels: patch

#591 Update Formation dependencies to latest version (7.0.4)
  packages/react-components/package.json
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: patch

#590 Add vads-align-self class to css-library
  packages/css-library/src/tokens/flexbox.scss
  packages/css-library/src/utilities/flexbox.scss
Labels: minor
