Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-07, with the labels that each got.

#477 Rename master branch to main
  .github/workflows/codeql.yml
  .github/workflows/node.js.yml
  .github/workflows/publish-storybook.yml
  README.md
  packages/core/README.md
  packages/design-system-dashboard-cli/README.md
  packages/react-components/scripts/prepublish.js
  packages/storybook/stories/IconBase.stories.jsx
  packages/storybook/stories/va-date.stories.jsx
  packages/storybook/stories/va-memorable-date.stories.jsx
Labels: ignore-for-release

#472 Add va-button-pair component
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-button-pair.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.css
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
Labels: minor

#478 Remove Banner, CollapsiblePanel, PromoBanner and TextArea React components
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Banner/Banner.jsx
  packages/react-components/src/components/Banner/Banner.mdx
  packages/react-components/src/components/Banner/Banner.unit.spec.jsx
  packages/react-components/src/components/CollapsiblePanel/CollapsiblePanel.jsx
  packages/react-components/src/components/CollapsiblePanel/CollapsiblePanel.mdx
  packages/react-components/src/components/CollapsiblePanel/CollapsiblePanel.unit.spec.jsx
  packages/react-components/src/components/CollapsiblePanel/static-markup.stories.js
  packages/react-components/src/components/PromoBanner/PromoBanner.jsx
  packages/react-components/src/components/PromoBanner/PromoBanner.mdx
  packages/react-components/src/components/PromoBanner/PromoBanner.unit.spec.jsx
  packages/react-components/src/components/TextArea/TextArea.jsx
  packages/react-components/src/components/TextArea/TextArea.mdx
  packages/react-components/src/components/TextArea/TextArea.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/TextArea.stories.jsx
  yarn.lock
Labels: ignore-for-release

#479 Add spacing and font tokens
  packages/css-library/tokens/fonts.json
  packages/css-library/tokens/spacing.json
Labels: ignore-for-release

#480 Add I18n linting
  README.md
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/web-components/.eslintrc.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx
  packages/web-components/src/components/va-banner/va-banner.tsx
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/components/va-search-input/va-search-input.tsx
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/utils/date-utils.ts
  packages/web-components/src/utils/modal.ts
  yarn.lock
Labels: ignore-for-release

#483 va-button uses aria-label only when a value is given
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
Labels: patch

#485 Remove unneeded aria-live when errors occur
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#484 Remove aria-labelledby in form controls
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
Labels: patch

#487 Token library outputs CSS variables
  packages/css-library/.gitignore
  packages/css-library/config.json
Labels: ignore-for-release

#481 Add va-link component
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.css
  packages/web-components/src/components/va-link/va-link.tsx
Labels: minor

#488 Bump puppeteer version
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#486 Associate date errors with sub components
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#494 fix link to memorable date docs
  packages/storybook/stories/additional-docs.js
Labels: ignore-for-release

#489 Add aria-invalid to most form components
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#492 Add tty prop to telephone component
  packages/core/package.json
  packages/storybook/stories/va-telephone.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: minor

#496 style: update va-breadcrumbs padding
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css
Labels: patch

#473 Improve i18n language detection
  packages/core/package.json
  packages/core/src/i18n/i18n-setup.js
  packages/react-components/package.json
  packages/web-components/package.json
Labels: patch

#498 style: add active styling for secondary and back va-button variants
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-button/va-button.css
Labels: patch

#499 Add nowrap to telephone component CSS
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-telephone/va-telephone.css
Labels: patch

#495 fix: text does not overlap icon in alerts
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/va-alert.css
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch
