Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-11, with the labels that each got.

#557 Fix screenreader not reading va-modal content in va-omb-info
  packages/storybook/stories/wc-helpers.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
Labels: patch

#556 Add SMS option to va-telephone component
  packages/storybook/stories/va-telephone.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: minor

#559 Translate "va-checkbox", "va-checkbox-group", "va-number-input" and "va-radio" component
  packages/core/package.json
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: minor

#560 Prepare css-library for publishing
  .github/workflows/publish.yml
Labels: ignore-for-release

#566 Update contact prop documentation
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: patch

#565 Spanish translation for va-memorable-date & va-text-input
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/storybook/stories/va-memorable-date.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#568 Update va-omb-info maturity and location in Storybook
  packages/storybook/stories/va-omb-info.stories.jsx
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
Labels: ignore-for-release

#574 Added autocomplete prop to va-text-input
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#570 add aria-label to va-pagination navigation landmark
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#577 Add Storybook style overrides for USWDS v3 components
  packages/storybook/.storybook/preview.js
  packages/storybook/.storybook/style.scss
Labels: ignore-for-release

#582 va-radio: add part attr to legend
  packages/web-components/package.json
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: enhancement, minor
