Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-03, with the labels that each got.

#284 35102/Banner Web Component
  packages/core/package.json
  packages/storybook/stories/va-banner.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
  packages/web-components/src/components/va-banner/test/va-banner.spec.ts
  packages/web-components/src/components/va-banner/va-banner.css
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: minor

#308 Hotfix Va-Banner Storybook Type Dropdown
  packages/storybook/stories/va-banner.stories.jsx
Labels: ignore-for-release

#309 Update axe-core and axe-core/puppeteer dependencies to latest
  packages/react-components/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#302 Update npm token for publishing
  .github/workflows/publish.yml
Labels: ignore-for-release

#291 Add responsive table web component
  packages/core/package.json
  packages/storybook/stories/va-table.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-row.css
  packages/web-components/src/components/va-table/va-table-row.tsx
  packages/web-components/src/components/va-table/va-table.css
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: minor

#310 36950 Storybook Upgrade Webpack 5
  package.json
  packages/react-components/package.json
  packages/react-components/testing/karma.conf.js
  packages/storybook/.storybook/main.js
  packages/storybook/package.json
  yarn.lock
Labels: ignore-for-release

#312 35709 Yarn Version Plugin
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarnrc.yml
  README.md
Labels: ignore-for-release

#311 4679 Progress Bars add in aria-valuetext
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-progress-bar/test/va-progress-bar.e2e.ts
  packages/web-components/src/components/va-progress-bar/va-progress-bar.tsx
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: patch

#297 35152 Promo Banner Web Component
  packages/core/package.json
  packages/storybook/stories/va-promo-banner.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-promo-banner/test/va-promo-banner.e2e.ts
  packages/web-components/src/components/va-promo-banner/va-promo-banner.css
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: minor

#315 36385 Checkbox Group axe check test in error state
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
Labels: patch

#316 35157 Promo Banner Padding Class on Body for Footer Spacing
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-promo-banner/va-promo-banner.css
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: patch

#298 35255 va modal dev
  packages/core/package.json
  packages/storybook/stories/va-modal.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal-slot.css
  packages/web-components/src/components/va-modal/va-modal.css
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/global/main.css
  packages/web-components/src/global/variables.css
  packages/web-components/src/mixins/focusable.css
  yarn.lock
Labels: minor

#313 36964 Va Telephone Vanity Numbers
  packages/core/package.json
  packages/storybook/stories/va-telephone.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: patch

#317 20488 Accordions Expand Collapse All
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion.css
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#319 Add Chromatic link to PR
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/chromatic-link.yml
  README.md
  packages/storybook/stories/AcceptTermsPrompt.stories.jsx
Labels: ignore-for-release

#323 Revert "20488 Accordions Expand Collapse All"
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion.css
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: ignore-for-release

#324 chore: increment patch version
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#321 34435 Remove React Focus Lock Dependency
  packages/core/package.json
  packages/react-components/package.json
  yarn.lock
Labels: patch

#330 Update branch naming documentation
  README.md
Labels: ignore-for-release

#326 38305 Remove SearchMenu React Component
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/SearchMenu/SearchMenu.jsx
  packages/react-components/src/components/SearchMenu/SearchMenu.mdx
  packages/react-components/src/components/SearchMenu/SearchMenu.unit.spec.jsx
  packages/react-components/src/components/SystemDownView/SystemDownView.mdx
  packages/react-components/src/index.js
  packages/storybook/stories/SearchMenu.stories.jsx
Labels: major

#332 Add helper function for va-table migration
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/index.ts
  packages/web-components/src/utils/__snapshots__/table-migration.spec.tsx.snap
  packages/web-components/src/utils/table-migration.spec.tsx
  packages/web-components/src/utils/table-migration.tsx
Labels: minor

#336 Copy dashboard-cli package into monorepo
  packages/design-system-dashboard-cli/.env.json
  packages/design-system-dashboard-cli/.eslintrc.json
  packages/design-system-dashboard-cli/.gitignore
  packages/design-system-dashboard-cli/.husky/.gitignore
  packages/design-system-dashboard-cli/.husky/pre-commit
  packages/design-system-dashboard-cli/.prettierrc.json
  packages/design-system-dashboard-cli/README.md
  packages/design-system-dashboard-cli/img/filtered-result.png
  packages/design-system-dashboard-cli/img/multiple-search.png
  packages/design-system-dashboard-cli/img/regex-search.png
  packages/design-system-dashboard-cli/img/terminal-output.png
  packages/design-system-dashboard-cli/package.json
  packages/design-system-dashboard-cli/src/display-search-data.js
  packages/design-system-dashboard-cli/src/env.js
  packages/design-system-dashboard-cli/src/find-ds-components.js
  packages/design-system-dashboard-cli/src/find-form-apps.js
  packages/design-system-dashboard-cli/src/flatten-data.js
  packages/design-system-dashboard-cli/src/get-manifest.js
  packages/design-system-dashboard-cli/src/non-form-app-uses.js
  packages/design-system-dashboard-cli/src/search-files.js
  packages/design-system-dashboard-cli/src/to-csv.js
  packages/design-system-dashboard-cli/src/to-sql.js
  packages/design-system-dashboard-cli/src/today.js
  yarn.lock
Labels: ignore-for-release

#340 39117 Update Minimist Resolution
  package.json
  yarn.lock
Labels: ignore-for-release

#339 37935 Remove React Components from Storybook
  packages/storybook/stories/AdditionalInfo.stories.jsx
  packages/storybook/stories/AlertBox.stories.jsx
  packages/storybook/stories/CollapsiblePanel.stories.jsx
  packages/storybook/stories/LoadingIndicator.stories.jsx
  packages/storybook/stories/Telephone.stories.jsx
Labels: ignore-for-release
