Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-04, with the labels that each got.

#322 Add slot to va-text-input
  packages/core/package.json
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#341 va-on-this-page hide link to h2 without id
  packages/storybook/stories/va-on-this-page.stories.jsx
  packages/web-components/src/components/va-on-this-page/test/va-on-this-page.e2e.ts
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
Labels: patch

#318 Add sorting functionality to va-table component
  packages/storybook/stories/va-table.stories.jsx
  packages/web-components/src/assets/sort-arrow-down.svg
  packages/web-components/src/assets/sort-arrow-up.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-row.css
  packages/web-components/src/components/va-table/va-table-slot.css
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/global/main.css
  packages/web-components/src/utils/dom-sort.spec.ts
  packages/web-components/src/utils/dom-sort.ts
Labels: minor

#348 Add comment to prop doc about IE11 support
  packages/web-components/src/components/va-table/va-table.tsx
Labels: ignore-for-release

#342 Add analytics to va-on-this-page
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-on-this-page/test/va-on-this-page.e2e.ts
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
Labels: minor

#353 Updates yarn to 3.2 to pickup a fix to a stream closure issue. [Fixes #352]
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/releases/yarn-3.0.2.cjs
  .yarn/releases/yarn-3.2.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ignore-for-release

#357 Add initial tests for dashboard-cli
  .github/workflows/node.js.yml
  packages/design-system-dashboard-cli/.yarnrc.yml
  packages/design-system-dashboard-cli/__mocks__/fs.js
  packages/design-system-dashboard-cli/jest.config.js
  packages/design-system-dashboard-cli/package.json
  packages/design-system-dashboard-cli/test/__snapshots__/to-csv.spec.js.snap
  packages/design-system-dashboard-cli/test/flatten-data.spec.js
  packages/design-system-dashboard-cli/test/get-manifest.spec.js
  packages/design-system-dashboard-cli/test/search-files.spec.js
  packages/design-system-dashboard-cli/test/to-csv.spec.js
  packages/design-system-dashboard-cli/test/to-sql.spec.js
  yarn.lock
Labels: ignore-for-release

#325 Add va-search web component
  packages/storybook/.storybook/manager.js
  packages/storybook/stories/va-search.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-search/test/va-search.e2e.ts
  packages/web-components/src/components/va-search/va-search.css
  packages/web-components/src/components/va-search/va-search.tsx
  packages/web-components/src/mixins/focusable.css
Labels: minor

#346 Add infrastructure for internationalization
  packages/core/package.json
  packages/core/src/i18n/i18n-setup.js
  packages/core/src/i18n/language-detector.js
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/scripts/build.js
  packages/storybook/.storybook/preview.js
  packages/web-components/package.json
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/index.ts
  yarn.lock
Labels: minor

#366 Bump Formation v7.0.1
  packages/react-components/package.json
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#369 Add subtitle and action link for Modal in Storybook
  packages/storybook/stories/va-modal.stories.jsx
Labels: ignore-for-release

#370 39872 Alert Documentation SB
  packages/storybook/stories/va-alert.stories.jsx
  packages/web-components/src/components/va-alert/va-alert.css
Labels: ignore-for-release

#371 Add subtitle and link for Radio buttons in Storybook
  packages/storybook/stories/va-radio.stories.jsx
Labels: ignore-for-release

#374 Add subtitle, link and story for CheckboxGroup and Checkbox
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
Labels: ignore-for-release

#375 Add placeholder translations for a few components
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
Labels: ignore-for-release

#377 Update codeowners
  .github/CODEOWNERS
Labels: ignore-for-release

#379 39969 Storybook Pagination Link Documentation
  packages/storybook/stories/va-pagination.stories.jsx
Labels: ignore-for-release

#380 39967 Loading Indicator Storybook Documentation
  packages/storybook/stories/va-loading-indicator.stories.jsx
Labels: ignore-for-release

#381 39862 Additional Info SB Documentation
  packages/storybook/stories/va-additional-info.stories.jsx
Labels: ignore-for-release

#349 39550 va-number-input Web Component
  packages/core/package.json
  packages/storybook/stories/va-number-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.css
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-text-input/va-text-input.css
Labels: minor

#384 Fix links to design system docs
  packages/storybook/stories/events.js
Labels: ignore-for-release

#383 39860 Accordion Documentation Update SB
  packages/storybook/stories/va-accordion.stories.jsx
Labels: ignore-for-release

#378 Add subtitle, link and success state example for va-text-input
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/va-text-input.css
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: ignore-for-release

#382 Add subtitle and link for Select Box
  packages/storybook/stories/va-select.stories.jsx
Labels: ignore-for-release

#387 Bump version Patch 2.12.1
  packages/core/package.json
  packages/web-components/package.json
Labels: patch

#392 Update README with bindings build step and cli description
  README.md
Labels: ignore-for-release

#395 39738 Number Input Docs Link Fix and Input El fix
  packages/core/package.json
  packages/storybook/stories/va-number-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: patch

#396 Fix for JSDoc usage of <input> in docs
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.css
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#397 Updates va-additional-info to use primary alt darkest to pass WCAG
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/global/variables.css
Labels: patch

#400 Add subtitle and link to DS for va-back-to-top
  packages/storybook/stories/va-back-to-top.stories.jsx
Labels: ignore-for-release

#399 Replace vaBlur with native blur event for va-checkbox
  packages/core/package.json
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: major

#391 Update va-search-input to emit the correct target value
  packages/storybook/stories/va-search-input.stories.jsx
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: ignore-for-release

#363 Use native events for va-text-input
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: major
