Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-02, with the labels that each got.

#277 Remove placeholder prop from va-text-input
  packages/core/package.json
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: major

#279 Match release note labels to required labels
  .github/release.yml
Labels: ignore-for-release

#270 Add web component events documentation on Storybook
  packages/storybook/stories/events.js
  packages/storybook/stories/va-accordion.stories.jsx
  packages/storybook/stories/va-alert.stories.jsx
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/storybook/stories/wc-helpers.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-progress-bar/va-progress-bar.tsx
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: ignore-for-release

#276 601 Radio Option Unique Id Prop
  packages/core/package.json
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
Labels: patch

#278 36046 va-accordion IE11 bugs
  README.md
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#280 Fix va-alert heading to not announce as clickable when using NVDA
  packages/storybook/.storybook/preview.js
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch

#282 Fix Storybook stories render
  packages/storybook/stories/wc-helpers.jsx
Labels: patch

#281 Update va-progress-bar aria-label when percent is used to round
  packages/storybook/stories/va-progress-bar.stories.jsx
  packages/web-components/src/components/va-progress-bar/test/va-progress-bar.e2e.ts
  packages/web-components/src/components/va-progress-bar/va-progress-bar.tsx
Labels: patch

#283 Fix va-additional-info content overflow
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
Labels: patch

#288 533 Storybook React RadioButtons Error Message Display
  packages/storybook/stories/RadioButtons.stories.jsx
Labels: patch

#285 Fix CSS in Stencil dev server for IE11
  packages/web-components/src/index.html
Labels: ignore-for-release

#290 36826/Sass-Loader-Storybook
  packages/react-components/package.json
  packages/storybook/package.json
  yarn.lock
Labels: ignore-for-release

#293 36826/Upgrade Storybook from 6.3 to 6.4
  packages/storybook/.storybook/main.js
  packages/storybook/.storybook/preview.js
  packages/storybook/package.json
  yarn.lock
Labels: ignore-for-release

#292 Resolutions for Security Vulnerability Dependencies
  package.json
  yarn.lock
Labels: ignore-for-release

#295 Move CONTACTS table to telephone web component story
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/index.js
  packages/storybook/stories/Telephone.stories.jsx
  packages/storybook/stories/va-telephone.stories.jsx
Labels: patch

#275 Add va-pagination component
  packages/core/package.json
  packages/storybook/stories/va-pagination.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.css
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: minor

#294 Fix va-breadcrumbs page reload when using Link elements
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs-slot.css
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
  packages/web-components/src/global/main.css
Labels: patch

#300 Adjust peer dependencies to remove warnings
  packages/core/package.json
  packages/react-components/package.json
  packages/web-components/package.json
  yarn.lock
Labels: patch

#301 35769 Fix Analytics Component Name
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch

#299 Fix Table axe check aria-label
  packages/react-components/src/components/Table/Table.jsx
Labels: patch

#304 632/remove process list react component
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/ProcessList/ProcessList.jsx
  packages/react-components/src/components/ProcessList/ProcessList.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/ProcessList.stories.jsx
  yarn.lock
Labels: major

#305 add upgrade resolution for prismjs
  package.json
  yarn.lock
Labels: ignore-for-release

#306 Deleting back to top deprecated item
  packages/storybook/stories/back-to-top.stories.mdx
Labels: ignore-for-release

#307 Relatively position full-width alert close above 1024px only
  packages/web-components/src/components/va-alert/va-alert.css
Labels: patch
