Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-06, with the labels that each got.

#451 Ensure i18next is initialized in TextInput & Select
  packages/react-components/package.json
  packages/react-components/src/components/Select/Select.jsx
  packages/react-components/src/components/TextInput/TextInput.jsx
Labels: patch

#450 Update segmented progress bar guidance link
  packages/storybook/stories/additional-docs.js
Labels: ignore-for-release

#455 change sign in alert button color to green
  packages/storybook/stories/va-alert.stories.jsx
Labels: ignore-for-release

#438 843 va-date Text Inputs
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-date-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date-text-input/test/va-date-text-input.e2e.ts
  packages/web-components/src/components/va-date-text-input/va-date-text-input.css
  packages/web-components/src/components/va-date-text-input/va-date-text-input.tsx
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#447 Add button web component
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-button.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.css
  packages/web-components/src/components/va-button/va-button.tsx
Labels: minor

#456 Add disabled styling and story for va-button
  packages/storybook/stories/va-button.stories.jsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.css
  packages/web-components/src/components/va-button/va-button.tsx
Labels: ignore-for-release

#452 Demo CSS utilities based on USWDS 3
  packages/css-library/.gitignore
  packages/css-library/.yarnrc.yml
  packages/css-library/README.md
  packages/css-library/package.json
  packages/css-library/src/stylesheets/elements.scss
  packages/css-library/src/stylesheets/fonts.scss
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/tokens/color.scss
  packages/css-library/src/utilities/_index.scss
  packages/css-library/src/utilities/background-color.scss
  packages/css-library/src/utilities/color.scss
  packages/css-library/src/utilities/settings.scss
  yarn.lock
Labels: ignore-for-release

#448 877 va-date Web Component Enhancements
  packages/core/package.json
  packages/storybook/stories/va-date-text-input.stories.jsx
  packages/storybook/stories/va-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-date-text-input/va-date-text-input.tsx
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#458 41424 Storybook Introduction Page Links
  packages/storybook/.storybook/style.scss
  packages/storybook/stories/introduction.stories.mdx
Labels: ignore-for-release

#459 Update Storybook canvas documentation
  packages/storybook/stories/how-to-use-storybook.stories.mdx
  packages/storybook/stories/images/canvas-accessibility.png
  packages/storybook/stories/images/canvas-addons.png
  packages/storybook/stories/images/canvas-controls.png
  packages/storybook/stories/images/canvas-html.png
  packages/storybook/stories/images/canvas-measure.png
  packages/storybook/stories/images/canvas-other.png
  packages/storybook/stories/images/canvas-outline.png
  packages/storybook/stories/images/canvas-story.png
  packages/storybook/stories/images/canvas-tab.png
  packages/storybook/stories/images/canvas-toggle-background.png
  packages/storybook/stories/images/canvas-toolbar.png
  packages/storybook/stories/images/canvas-viewport.png
  packages/storybook/stories/images/canvas-vision.png
  packages/storybook/stories/images/canvas-zoom.png
  packages/storybook/stories/images/canvas.png
Labels: ignore-for-release

#461 Add web component native events docs link
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#460 918 form controls
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.css
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.css
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.css
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.css
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/va-text-input.css
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#457 Add monthyear date variant
  packages/core/package.json
  packages/storybook/stories/va-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#462 Update va-button to be focusable when disabled
  packages/storybook/stories/va-button.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
Labels: patch

#466 Fix styling for va-select and va-text-input when required is true
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-select/va-select.css
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.css
  packages/web-components/src/components/va-textarea/va-textarea.css
Labels: patch

#469 Remove unnecessary margin on va-alert-expandable
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
Labels: patch

#470 Prevent breadcrumb line break on mobile
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs-slot.css
Labels: patch

#463 Remove redundant textarea attribute & validate maxlength
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#467 change name of va-date-text-input to va-memorable-date
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-memorable-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.css
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: minor

#468 Display selected option when value is changed programmatically
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-select/va-select.tsx
Labels: patch
