Repository department-of-veterans-affairs/component-library, pull requests merged in 2022-08, with the labels that each got.

#497 fix: web components announce alerts
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-progress-bar/test/va-progress-bar.e2e.ts
  packages/web-components/src/components/va-progress-bar/va-progress-bar.css
  packages/web-components/src/components/va-progress-bar/va-progress-bar.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.css
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#491 Add va-omb-info web component
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-modal.stories.jsx
  packages/storybook/stories/va-omb-info.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.css
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-omb-info/test/va-omb-info.e2e.ts
  packages/web-components/src/components/va-omb-info/va-omb-info.css
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
Labels: minor

#501 Updating form web component error styles to align with USWDS.
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.css
  packages/web-components/src/components/va-checkbox/va-checkbox.css
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-memorable-date/va-memorable-date.css
  packages/web-components/src/components/va-number-input/va-number-input.css
  packages/web-components/src/components/va-radio/va-radio.css
  packages/web-components/src/components/va-select/va-select.css
  packages/web-components/src/components/va-text-input/va-text-input.css
  packages/web-components/src/components/va-textarea/va-textarea.css
  packages/web-components/src/mixins/form-field-error.css
Labels: patch

#505 Replace the "Date of Birth" label with a real one
  packages/storybook/stories/va-date.stories.jsx
Labels: ignore-for-release

#509 Move aria attributes for va-modal to host
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#510 Fixes for va-alert-expandable
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
  packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
Labels: patch

#503 chore: add v3 border, display and font utilities
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/tokens/border.scss
  packages/css-library/src/tokens/display.scss
  packages/css-library/src/tokens/font.scss
  packages/css-library/src/utilities/_index.scss
  packages/css-library/src/utilities/border.scss
  packages/css-library/src/utilities/display.scss
  packages/css-library/src/utilities/font.scss
  packages/css-library/src/utilities/settings.scss
Labels: ignore-for-release

#506 Rework date validation
  packages/core/package.json
  packages/storybook/stories/va-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#508 chore: add height, line-height, text-align, text-decoration and width utilities
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/tokens/height.scss
  packages/css-library/src/tokens/line-height.scss
  packages/css-library/src/tokens/text-align.scss
  packages/css-library/src/tokens/text-decoration.scss
  packages/css-library/src/tokens/width.scss
  packages/css-library/src/utilities/_index.scss
  packages/css-library/src/utilities/height.scss
  packages/css-library/src/utilities/line-height.scss
  packages/css-library/src/utilities/settings.scss
  packages/css-library/src/utilities/text-align.scss
  packages/css-library/src/utilities/text-decoration.scss
  packages/css-library/src/utilities/width.scss
Labels: ignore-for-release

#504 chore: add flex, position and visibility v3 utilities
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/tokens/flexbox.scss
  packages/css-library/src/tokens/position.scss
  packages/css-library/src/tokens/visibility.scss
  packages/css-library/src/utilities/_index.scss
  packages/css-library/src/utilities/flexbox.scss
  packages/css-library/src/utilities/position.scss
  packages/css-library/src/utilities/settings.scss
  packages/css-library/src/utilities/visibility.scss
Labels: ignore-for-release

#507 Create a File Input web component
  packages/core/package.json
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-file-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-file-input/test/1x1.png
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.css
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#512 Build v3 utility classes: Margins, Measure, and Padding
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/tokens/margin.scss
  packages/css-library/src/tokens/measure.scss
  packages/css-library/src/tokens/padding.scss
  packages/css-library/src/utilities/_index.scss
  packages/css-library/src/utilities/margin.scss
  packages/css-library/src/utilities/measure.scss
  packages/css-library/src/utilities/padding.scss
  packages/css-library/src/utilities/settings.scss
Labels: ignore-for-release

#517 Fix va-modal for Cypress
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.css
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#521 Fix visual defect in Safari for the va-alert component
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/va-alert.css
Labels: patch

#519 Fix va-modal teardown crash
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#520 Remove fullwidth alert story & update banner stories
  packages/storybook/stories/va-alert.stories.jsx
  packages/storybook/stories/va-banner.stories.jsx
Labels: ignore-for-release

#522 Fix va-modal styling
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.css
Labels: patch

#523 Translate "On this page" component
  packages/core/package.json
  packages/core/src/i18n/i18n-setup.js
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/core/src/i18n/translations/tl.js
  packages/storybook/stories/va-on-this-page.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-on-this-page/test/va-on-this-page.e2e.ts
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
Labels: minor
