Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-08, with the labels that each got.

#774 va-memorable-date: Fix hint text not reading for screen readers (uswds variation)
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#779 add formation overrides import to icon sass
  packages/storybook/stories/va-icon-uswds.stories.jsx
  packages/web-components/src/components/va-icon/va-icon.scss
Labels: patch

#780 v3 memorable-date: fix bugs with responsiveness
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
Labels: patch

#770 Add uswds va-process-list
  packages/storybook/stories/va-process-list-uswds.stories.jsx
  packages/storybook/stories/va-process-list.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/assets/green-check.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
  packages/web-components/src/components/va-process-list/test/va-process-list.e2e.ts
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-process-list/va-process-list-item.tsx
  packages/web-components/src/components/va-process-list/va-process-list.css
  packages/web-components/src/components/va-process-list/va-process-list.scss
  packages/web-components/src/components/va-process-list/va-process-list.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/global/_variables.scss
  packages/web-components/src/global/variables.css
Labels: minor

#753 remove deprecated react checkboxgroup component files
  packages/core/package.json
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/CheckboxGroup/CheckboxGroup.jsx
  packages/react-components/src/components/CheckboxGroup/CheckboxGroup.mdx
  packages/react-components/src/components/CheckboxGroup/CheckboxGroup.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#782 va-accordion: Deep linking not working
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
Labels: patch

#783 1901 misaligned va-memorable-date field
  packages/web-components/package.json
  packages/web-components/src/components/va-date/va-date.css
Labels: patch

#785 (bug): make html header tag lowercase
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-notification/va-notification.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: patch

#789 fix: only add margin for when additional info is open
  packages/web-components/package.json
  packages/web-components/src/components/va-additional-info/va-additional-info.css
Labels: patch

#790 va-pagination: Add optional chaining to activeElement blur
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#791 memorable-date - Fix date validation messages, focus invalid fields (NVDA/screen reader bug)
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#786 va-radio-option: Set tab index to -1 for radio button input
  packages/web-components/package.json
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
Labels: patch

#792 CSS Library Setup and generate basic token files
  packages/css-library/.gitignore
  packages/css-library/README.md
  packages/css-library/config.js
  packages/css-library/config.json
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/tokens/border.scss
  packages/css-library/src/tokens/color.scss
  packages/css-library/src/tokens/flex-grid.scss
  packages/css-library/src/tokens/flexbox.scss
  packages/css-library/src/tokens/font.scss
  packages/css-library/src/tokens/margin.scss
  packages/css-library/src/tokens/padding.scss
  yarn.lock
Labels: ignore-for-release

#788 va-text-input, va-number-input, va-textarea: Hint text a11y updates and add message-aria-describedby
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/storybook/stories/va-textarea-uswds.stories.jsx
  packages/storybook/stories/va-textarea.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#797 memorable-date: storybook story custom validation safari bug
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
Labels: ignore-for-release

#800 Fix spelling in README
  README.md
Labels: ignore-for-release

#799 va-textarea | Fix error span id & add tests
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: bug, patch

#802 Figma colors token
  packages/css-library/README.md
  packages/css-library/config.js
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/package.json
  yarn.lock
Labels: ignore-for-release

#794 add va-pagination uswds
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/storybook/stories/va-pagination-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.scss
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/utils/utils.ts
Labels: minor

#806 va-memorable-date & va-text-input: Remove unnecessary input message
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#805 va-segmented-progress-bar - staging review accessibility
  packages/storybook/stories/va-segmented-progress-bar-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: patch

#809 update stencil config to copy static assets to dist folder during build
  packages/web-components/stencil.config.ts
Labels: patch

#811 add back inputmode prop to va-number-input and adjust tests and stories
  packages/core/package.json
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: patch

#815 va-accordion: change line-height to 1.15
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
Labels: patch

#810 Introducing a new script to copy USWDS tokens
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
Labels: ignore-for-release

#814 Initial commit of generated stylesheets
  packages/css-library/dist/elements.css
  packages/css-library/dist/elements.css.map
  packages/css-library/dist/elements.min.css
  packages/css-library/dist/fonts.css
  packages/css-library/dist/fonts.css.map
  packages/css-library/dist/fonts.min.css
  packages/css-library/dist/utilities.css
  packages/css-library/dist/utilities.css.map
  packages/css-library/dist/utilities.min.css
Labels: ignore-for-release

#821 va-additional-info update lifecycle hook for height computation
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
Labels: patch

#818 Update Colors based on feedback
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/color.json
  packages/storybook/stories/styles/va-icon.scss
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#816 2009 fix month inputs
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
Labels: patch

#817 va-checkbox | Add description id to aria-describedby
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#822 Update wc-helpers.jsx
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#823 bump core version to 20.0.0
  packages/core/package.json
Labels: major

#825 remove gibill accent
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/dist/utilities.css
  packages/css-library/dist/utilities.css.map
  packages/css-library/src/tokens/color.scss
Labels: minor

#824 1788 modals not sizing
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.scss
Labels: patch

#827 va-accordion: Load correct font family for expand/collapse
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion.scss
Labels: patch
