Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-01, with the labels that each got.

#594 Add variables.scss file to obtain USWDS v3 colors
  packages/web-components/src/global/_variables.scss
  packages/web-components/stencil.config.ts
Labels: minor

#595 Add description and tile display to va-radio-option
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
Labels: minor

#596 va-breadcrumbs: Add handling of dynamic slot changes of breadcrumb items.
  packages/core/package.json
  packages/storybook/stories/va-breadcrumbs.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: minor

#598 Add focus style to va-alert close button
  packages/web-components/src/components/va-alert/va-alert.css
Labels: patch

#601 Tagalog translation for va-memorable-date & va-text-input
  packages/core/src/i18n/translations/tl.js
  packages/storybook/stories/va-memorable-date.stories.jsx
Labels: minor

#603 Add part attribute to textarea component (#1410)
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: enhancement, minor

#606 Add VA favicons to Storybook
  packages/storybook/.storybook/manager-head.html
Labels: ignore-for-release

#602 Accessibility updates to va-pagination to support Voice Control
  packages/core/package.json
  packages/storybook/stories/va-pagination.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#607 Add translation to date error message validators
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/core/src/i18n/translations/tl.js
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#612 Upgrade React to v18 in component-library
  packages/core/package.json
  yarn.lock
Labels: minor
