Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-06, with the labels that each got.

#707 Add width option to va-text-input
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/mixins/uswds-input-width.scss
Labels: patch

#709 1713 vacheckbox issue
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
Labels: patch

#708 Add width option to va-number-input
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: patch

#702 Add va-notification web component
  packages/core/package.json
  packages/storybook/stories/va-notification.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/va-link.tsx
  packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
  packages/web-components/src/components/va-notification/va-notification.scss
  packages/web-components/src/components/va-notification/va-notification.tsx
Labels: minor

#714 Upgrade @department-of-veterans-affairs/formation version to ^7.0.8
  packages/react-components/package.json
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: patch

#713 add/convert maintenance banner to a web component
  packages/storybook/stories/MaintenanceBanner.stories.jsx
  packages/storybook/stories/va-maintenance-banner.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-maintenance-banner/test/va-maintenance-banner.e2e.ts
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.scss
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#719 Allow month to be selected for va-memorable-date using 'month-select'
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: minor

#716 60122 va select inert
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-select/va-select.scss
Labels: minor

#721 Update for Chromatic Publish Action
  package.json
Labels: ignore-for-release

#718 Allow date field copy/paste with keyboard shortcut
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#717 Update va-table to support pagination
  packages/storybook/stories/va-table.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-slot.css
  packages/web-components/src/components/va-table/va-table.tsx
Labels: patch

#723 Core version bump to 16.4
  packages/core/package.json
Labels: ignore-for-release

#724 va-notification: align CLOSE text with card padding
  packages/web-components/src/components/va-notification/va-notification.scss
Labels: patch

#726 Accessibility fix for radio option width for va-radio-option.scss
  packages/web-components/package.json
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
Labels: patch

#729 va-table: Update MutationObserver for pagination
  packages/web-components/package.json
  packages/web-components/src/components/va-table/va-table.tsx
Labels: patch

#730 Removing accordion-item tabindex
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
Labels: patch

#731 Prevent screen reader from reading modal twice
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#732 va-memorable-date: Change two and four to 2 and 4
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/core/src/i18n/translations/tl.js
Labels: patch

#728 Add va-accordion USWDS v3 variation
  packages/storybook/stories/va-accordion-uswds.stories.jsx
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.css
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.scss
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: minor
