Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-12, with the labels that each got.

#969 va-checkbox-group: make legend font match design spec
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
Labels: patch

#962 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#966 va-modal: fix for screen readers when using Storybook
  packages/storybook/.storybook/preview.js
  packages/web-components/package.json
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
Labels: patch

#973 va-official-gov-banner: Fix for medium screens wrapping wrongly
  packages/web-components/package.json
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss
Labels: patch

#975 Update core version to v33.0.0 for release
  packages/core/package.json
Labels: major

#983 alternate release please install --test branch only
  .github/workflows/release.yml
  .release-please-manifest.json
  release-please-config.json
Labels: ignore-for-release

#981 Add custom CSS type selectors from Formation
  packages/css-library/dist/elements.css
  packages/css-library/dist/elements.css.map
  packages/css-library/src/stylesheets/elements.scss
Labels: ignore-for-release

#982 Add CSS type selectors from Formation to CSS Library
  packages/css-library/dist/elements.css
  packages/css-library/dist/elements.css.map
  packages/css-library/dist/print.css
  packages/css-library/dist/print.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/elements.scss
  packages/css-library/src/stylesheets/print.scss
  packages/css-library/tokens/breakpoints.json
  packages/css-library/tokens/color.json
Labels: ignore-for-release

#986 Update target branch of release-please
  .github/workflows/release.yml
Labels: ignore-for-release

#977 USWDS va-pagination not showing next/previous page in list
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#989 fix token name
  .github/workflows/release.yml
Labels: ignore-for-release

#979 va-breadcrumbs: add support for React Router via custom event
  packages/storybook/stories/va-breadcrumbs-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: minor

#1004 Alert V3 backround and boder color fix
  packages/web-components/src/components/va-alert/va-alert.scss
Labels: patch

#985 va-text-input & va-number-input: add new form pattern support to USWDS variations
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/wc-helpers.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/mixins/focusable.css
  packages/web-components/src/mixins/uswds-error-border.scss
  packages/web-components/src/utils/utils.ts
Labels: minor
