Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-07, with the labels that each got.

#725 Remove Table React component
  packages/core/package.json
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Table/Table.jsx
  packages/react-components/src/components/Table/Table.unit.spec.jsx
  packages/react-components/src/components/Table/test-data.js
  packages/react-components/src/index.js
  packages/storybook/stories/Table.stories.jsx
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-telephone.stories.jsx
  packages/web-components/src/index.ts
  packages/web-components/src/utils/__snapshots__/table-migration.spec.tsx.snap
  packages/web-components/src/utils/table-migration.spec.tsx
  packages/web-components/src/utils/table-migration.tsx
Labels: major

#735 sync va-memorable-date top margin with uswds
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
Labels: patch

#736 sync va-radio margin top with uswds
  packages/web-components/src/components/va-radio/va-radio.scss
Labels: patch

#737 sync margin top of checkbox-group with uswds
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
Labels: patch

#739 va-alert Storybook: Remove action link and add button for sign-in prompt
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/storybook/stories/va-alert.stories.jsx
Labels: ignore-for-release

#741 61157 - Remove role="alert" from va-notification. Update package.json versions
  packages/web-components/package.json
  packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
  packages/web-components/src/components/va-notification/va-notification.tsx
Labels: patch

#742 Maint. Banner staging review changes
  packages/storybook/stories/va-maintenance-banner.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-maintenance-banner/test/va-maintenance-banner.e2e.ts
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#743 Update styles to fix buttons from overflowing on modals (non-uswds)
  packages/storybook/stories/va-modal.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-button-pair/va-button-pair.scss
Labels: patch

#751 va-date & va-memorable-date: Switch to zero pad function
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: enhancement, patch

#750 va-memorable-date: Fix days of month calculation
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: bug, patch

#749 va-memorable-date: Fix clearing error message bug
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/storybook/stories/va-memorable-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: bug, patch

#746 va-back-to-top: Change button to anchor link
  packages/web-components/package.json
  packages/web-components/src/components/va-back-to-top/test/va-back-to-top.e2e.ts
  packages/web-components/src/components/va-back-to-top/va-back-to-top.css
  packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx
Labels: patch

#754 Added the mobile team to codeowners and tried to plan directories
  .github/CODEOWNERS
  .github/workflows/mobile-ci.yml
  .github/workflows/mobile-documentation.yml
  .github/workflows/mobile-publish.yml
  packages/mobile-components/.gitkeep
  packages/mobile-documentation/.gitkeep
  packages/mobile-icons/.gitkeep
  packages/mobile-linting/.gitkeep
  packages/mobile-tokens/.gitkeep
Labels: ignore-for-release

#755 va-notification - add dateTime prop
  packages/storybook/stories/va-notification.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
  packages/web-components/src/components/va-notification/va-notification.tsx
Labels: patch

#758 Update core to v17.0.1 for release
  packages/core/package.json
Labels: ignore-for-release

#762 va-checkbox - add message-aria-describedby property for optional additional message for screen readers
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#764 va-text-input (USWDS) add aria-described-by optional message
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#760 va-modal: Add button click analytics
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#767 va-checkbox, va-radio - override .usa white background color to be transparent
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
Labels: patch

#771 va-button - add alternate (green) version to primary button
  packages/css-library/tokens/color.json
  packages/css-library/tokens/fonts.json
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/storybook/stories/va-alert.stories.jsx
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/storybook/stories/va-button.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/global/_variables.scss
  packages/web-components/src/global/variables.css
Labels: minor

#763 Add charcount prop to va-text-input and va-textarea USWDS variations
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/va-textarea-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/utils/utils.ts
Labels: patch

#778 Check for node, tagName for va-loading-indicator
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
Labels: patch
