Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-11, with the labels that each got.

#922 2195 - Update memorable-date validation
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#934 Add banner role to minimal header
  .gitignore
  packages/web-components/src/components/va-minimal-header/test/va-minimal-header.spec.tsx
  packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx
Labels: patch

#933 Revert icon related changes
  .github/workflows/publish-storybook.yml
  packages/storybook/.storybook/main.js
Labels: ignore-for-release

#936 Add datadog action name to radio description
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
Labels: minor

#938 VaMinimalHeader: add alt attribute to img
  packages/web-components/src/components/va-minimal-header/test/va-minimal-header.spec.tsx
  packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx
Labels: patch

#941 2248 - Deprecating va-notification in storybook
  packages/storybook/stories/va-notification.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-notification/va-notification.tsx
Labels: patch

#942 update core to 31.0.1
  packages/core/package.json
Labels: ignore-for-release

#943 va-modal - 2219 font, icon, and responsiveness fix for v3
  packages/web-components/src/components/va-modal/va-modal.scss
Labels: patch

#939 va-breadcrumb removed react breadcrumb component
  packages/core/package.json
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Breadcrumbs/Breadcrumbs.jsx
  packages/react-components/src/components/Breadcrumbs/Breadcrumbs.mdx
  packages/react-components/src/components/Breadcrumbs/Breadcrumbs.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/Breadcrumbs.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#937 Va-minimal-footer: add component
  packages/storybook/stories/va-minimal-footer.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/assets/va-logo-white.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-minimal-footer/test/va-minimal-footer.e2e.ts
  packages/web-components/src/components/va-minimal-footer/test/va-minimal-footer.spec.tsx
  packages/web-components/src/components/va-minimal-footer/va-minimal-footer.scss
  packages/web-components/src/components/va-minimal-footer/va-minimal-footer.tsx
Labels: minor

#946 update package.json for publishing
  packages/css-library/package.json
Labels: major

#940 A11y improvements for va-crisis-line-modal, va-minimal-header, va-modal
  packages/web-components/src/components/va-crisis-line-modal/test/va-crisis-line-modal.e2e.ts
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.tsx
  packages/web-components/src/components/va-minimal-header/test/va-minimal-header.spec.tsx
  packages/web-components/src/components/va-minimal-header/va-minimal-header.scss
  packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#945 update web-components to use variables from css-library
  package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/global/_functions.scss
  packages/web-components/src/global/_variables.scss
  packages/web-components/src/global/main.css
  packages/web-components/src/global/variables.css
  packages/web-components/src/mixins/uswds-error-border.scss
  yarn.lock
Labels: minor

#947 va-search-input: add USWDS v3 variation
  packages/storybook/stories/va-search-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/assets/search--white.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.scss
  packages/web-components/src/components/va-search-input/va-search-input.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: minor

#949 #2239 remove banner landmark from promo banner
  packages/web-components/src/components/va-promo-banner/test/va-promo-banner.e2e.ts
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: patch

#952 Bump core to 32.1.0
  packages/core/package.json
Labels: ignore-for-release

#955 va-statement-of-truth: update storybook width display
  packages/storybook/stories/va-statement-of-truth-uswds.stories.jsx
  packages/storybook/stories/va-statement-of-truth.stories.jsx
Labels: ignore-for-release

#957 Fix issue with va-on-this-page left margin alignment
  packages/web-components/package.json
  packages/web-components/src/components/va-on-this-page/va-on-this-page.css
Labels: patch

#954 va-minimal-footer: add focus outline to logo
  packages/web-components/package.json
  packages/web-components/src/components/va-minimal-footer/va-minimal-footer.scss
Labels: patch

#959 Removing background-only section from V3 Alerts
  packages/storybook/stories/va-alert-uswds.stories.jsx
Labels: ignore-for-release

#964 Remove VA Mobile directories
  .github/CODEOWNERS
  packages/mobile-components/.gitkeep
  packages/mobile-documentation/.gitkeep
  packages/mobile-icons/.gitkeep
  packages/mobile-linting/.gitkeep
  packages/mobile-tokens/.gitkeep
Labels: ignore-for-release

#960 va-segmented-progress-bar: Hiding steps from JAWS
  packages/web-components/package.json
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: patch

#951 va-omb-info, va-crisis-line-modal, va-minimal-header: Fix for focus trapping
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.tsx
  packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
  packages/web-components/src/utils/modal.ts
Labels: patch

#968 update core version for release
  packages/core/package.json
Labels: ignore-for-release
