Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-05, with the labels that each got.

#689 Add va-segmented-progress-bar USWDS v3 variation
  packages/core/package.json
  packages/storybook/stories/va-segmented-progress-bar-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.scss
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
  packages/web-components/src/global/_formation_overrides.scss
  yarn.lock
Labels: minor

#691 va-date: Align year input with month and day inputs
  packages/web-components/package.json
  packages/web-components/src/components/va-date/va-date.css
Labels: patch

#692 va-textinput add inline hint to storybook
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
Labels: ignore-for-release

#688 Add icon support to va-accordion-item subheader
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.css
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
Labels: minor

#696 Text input label font-size fix for UXPin
  packages/web-components/package.json
  packages/web-components/src/components/va-text-input/va-text-input.scss
Labels: patch

#697 Fix va-banner displaying left border
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/global/_formation_overrides.scss
Labels: patch

#698 Adds a Sign in to start your application story to Alert.
  packages/storybook/stories/va-alert.stories.jsx
Labels: ignore-for-release

#701 Hotfix to loading indicator observer disconnect
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
Labels: patch

#695 Add va-card component
  packages/storybook/stories/va-card.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-card/test/va-card.e2e.ts
  packages/web-components/src/components/va-card/va-card.scss
  packages/web-components/src/components/va-card/va-card.tsx
Labels: minor

#704 Button icon font size override
  packages/web-components/package.json
  packages/web-components/src/global/_formation_overrides.scss
Labels: patch

#705 Formation - 7.0.7
  packages/react-components/package.json
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: minor

#706 Core version bump to 16.2.0
  packages/core/package.json
Labels: minor

#703 feat: Additional info v3
  packages/storybook/stories/va-additional-info-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
Labels: minor

#700 Updates to "Releasing" section of README - 1734
  README.md
Labels: ignore-for-release
