Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-02, with the labels that each got.

#608 Add the "Banner - Official Gov" web component
  packages/core/src/i18n/translations/en.js
  packages/core/src/i18n/translations/es.js
  packages/storybook/stories/va-official-gov-banner.stories.jsx
  packages/web-components/src/assets/icon-dot-gov.svg
  packages/web-components/src/assets/icon-https.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-official-gov-banner/test/va-official-gov-banner.e2e.ts
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
Labels: minor

#613 va-radio | Add property to include header inside legend
  packages/core/package.json
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: enhancement, minor

#615 Add aria-describedby-message prop to va-text-input
  packages/core/package.json
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#616 Fix va-text-input error message style
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/mixins/form-field-error.css
Labels: patch

#620 va-text-input: Update aria message prop name
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#619 va-official-gov-banner: Update mobile close icon so it matches USWDS
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss
Labels: patch

#623 Move ExpandingGroup React component to deprecated section in Storybook
  packages/storybook/stories/ExpandingGroup.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: ignore-for-release

#622 Formation overrides for va-text-input component
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/global/_functions.scss
  packages/web-components/src/global/_variables.scss
Labels: patch

#627 Add PR configuration checklist to PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#630 va-memorable-date: add hint property
  packages/core/package.json
  packages/storybook/stories/va-memorable-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.css
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: enhancement, minor

#624 Add va-checkbox and va-checkbox-group USWDS v3 variations
  packages/css-library/tokens/color.json
  packages/css-library/tokens/fonts.json
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.css
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/global/_functions.scss
  packages/web-components/src/global/_variables.scss
  packages/web-components/src/global/variables.css
Labels: minor

#626 Add "Source Sans Pro" to the USWDS v3 font-family stack
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/global/_settings.scss
Labels: patch

#633 va-radio-option: Fix long label wrapping
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
Labels: bug, fix, patch

#632 va-radio: Add Bitter font to wrapping header
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-radio/va-radio.scss
Labels: patch
