Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-09, with the labels that each got.

#830 va-radio: increase legend width to 480px
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: patch

#828 AdditionalInfo: remove AdditionalInfo React component and references
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/design-system-dashboard-cli/test/write-react-owners-to-csv.spec.js
  packages/react-components/index.js
  packages/react-components/src/components/AdditionalInfo/AdditionalInfo.jsx
  packages/react-components/src/components/AdditionalInfo/AdditionalInfo.mdx
  packages/react-components/src/components/AdditionalInfo/AdditionalInfo.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#833 Add Datadog privacy class to hide screen reader text
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: enhancement, patch

#835 va-accordion: use setAttribute instead of calling click on accordion buttons
  packages/storybook/stories/va-accordion-uswds.stories.jsx
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#834 memorable-date - remove focus logic on validation failures
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#840 61627 mem date selective errors
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#842 Add label-header-level to checkbox group
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/mixins/headers.css
Labels: enhancement, minor

#836 removes references to React Pagination component
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Pagination/Pagination.jsx
  packages/react-components/src/components/Pagination/Pagination.mdx
  packages/react-components/src/components/Pagination/Pagination.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/Pagination.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#841 storybook - update buttons in uswds stories to use uswds va-button
  packages/storybook/stories/va-accordion-uswds.stories.jsx
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/storybook/stories/va-breadcrumbs-uswds.stories.jsx
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/storybook/stories/va-modal-uswds.stories.jsx
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/storybook/stories/va-pagination-uswds.stories.jsx
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/storybook/stories/va-text-input-uswds.stories.jsx
Labels: ignore-for-release

#849 Core version bump to 21.0.0
  packages/core/package.json
Labels: ignore-for-release

#852 Remove empty mobile github workflows
  .github/CODEOWNERS
  .github/workflows/mobile-ci.yml
  .github/workflows/mobile-documentation.yml
  .github/workflows/mobile-publish.yml
Labels: ignore-for-release

#839 Adding a 'useDiv' flag to segmented progress bars
  packages/storybook/stories/va-segmented-progress-bar-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: patch

#851 va-telephone: Change extension prop from number to string type
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: patch

#860 va-radio, va-radio-option: Screen reader and keyboard navigation updates
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: patch

#858 Remove Telephone React component
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Telephone/Telephone.jsx
  packages/react-components/src/components/Telephone/Telephone.mdx
  packages/react-components/src/components/Telephone/Telephone.unit.spec.jsx
  packages/react-components/src/components/Telephone/patterns.js
  packages/react-components/src/index.js
  packages/web-components/src/contacts.ts
  packages/web-components/src/index.ts
Labels: major

#856 va-number-input: 2052 default number validation message
  packages/core/src/i18n/translations/en.js
  packages/web-components/package.json
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: patch

#859 Va-pagination: add handlers to uswds pagination component
  packages/storybook/stories/va-pagination-uswds.stories.jsx
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.scss
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#862 Bump core version to 21.0.2
  packages/core/package.json
Labels: ignore-for-release

#863 bump core version to 22.0.0
  packages/core/package.json
Labels: ignore-for-release

#850 va-statment-of-truth: add component to Design System
  packages/storybook/stories/va-statement-of-truth-uswds.stories.jsx
  packages/storybook/stories/va-statement-of-truth.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
Labels: minor

#861 Breadcrumb component - fixed left padding for v1
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
Labels: patch

#864 va-pagination: remove 'role=presentation' to fix axe check errors
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#867 add space back to number input
  packages/core/package.json
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: patch

#868 update to 23
  packages/core/package.json
Labels: ignore-for-release

#854 OMBInfo: remove React component
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/OMBInfo/OMBInfo.jsx
  packages/react-components/src/components/OMBInfo/OMBInfo.mdx
  packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/OMBInfo.stories.jsx
Labels: major

#870 Adding aria-label to V3 pagination
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#869 2011 default month select
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#873 Remove Telephone React folder from package
  packages/react-components/src/components/Telephone/contacts.js
Labels: ignore-for-release

#866 va-radio: Add aria-describedby to header
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: patch

#875 Github action to disallow zenhub links in PR descriptions
  .github/workflows/disallow-zenhub-link.yml
Labels: ignore-for-release

#877 va-modal: button widths, margin bug fix, storybook copy, title font family
  packages/storybook/stories/va-modal-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.scss
Labels: patch
