Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-10, with the labels that each got.

#884 va-breadcrumb: make current page a link to #content
  packages/web-components/package.json
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: patch

#878 Update va-memorable-date error message
  packages/core/src/i18n/translations/en.js
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#882 Remove Checkbox React component
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Checkbox/Checkbox.jsx
  packages/react-components/src/components/Checkbox/Checkbox.mdx
  packages/react-components/src/components/Checkbox/Checkbox.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/Checkbox.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#886 2076 Fix V3 and non-V3 CSS Selectors (Part 1)
  packages/web-components/src/components/va-accordion/va-accordion.scss
  packages/web-components/src/components/va-alert/va-alert-slot.css
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
  packages/web-components/src/components/va-button-pair/va-button-pair.scss
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
Labels: patch

#887 va-modal: Fix logic for aria-label, don't set aria-label if title is not provided
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#895 va-progress-list: Forward the USWDS settings to load Source Sans Pro
  packages/web-components/package.json
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-process-list/va-process-list.scss
Labels: patch

#892 va-memorable-date: Conditionally display name prop value
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#896 va-icon: Remove assetsDirs setting
  packages/web-components/package.json
  packages/web-components/src/components/va-icon/va-icon.tsx
Labels: patch

#885 2123 - Memorable Date validation bug
  packages/web-components/package.json
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#888 2076 Fix V3 and non-V3 CSS Selectors (Part 2)
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-pagination/va-pagination.scss
Labels: patch

#889 2076 Fix V3 and non-V3 CSS Selectors (Part 3)
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-process-list/va-process-list.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-select/va-select.scss
Labels: patch

#890 2076 Fix V3 and non-V3 CSS Selectors (Part 4)
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/mixins/focusable.css
  packages/web-components/src/mixins/form-field-error.css
  packages/web-components/src/mixins/uswds-error-border.scss
  packages/web-components/src/mixins/uswds-input-width.scss
Labels: patch

#904 Rollback memorable date
  packages/web-components/package.json
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.spec.ts
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#906 Update core version to v24.0.1 for release
  packages/core/package.json
Labels: ignore-for-release

#902 AlertBox and MaintenanceBanner: remove deprecated components
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/react-components/index.js
  packages/react-components/src/components/AlertBox/AlertBox.jsx
  packages/react-components/src/components/AlertBox/AlertBox.mdx
  packages/react-components/src/components/AlertBox/AlertBox.unit.spec.jsx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.jsx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.mdx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/MaintenanceBanner.stories.jsx
Labels: major

#907 Add back the contacts file to the React components package
  packages/core/package.json
  packages/react-components/package.json
  packages/react-components/src/components/Telephone/contacts.js
Labels: patch

#879 Remove LoadingIndicator React component
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.jsx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.mdx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#913 Revert deprecated React components from previous release
  packages/core/package.json
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/AlertBox/AlertBox.jsx
  packages/react-components/src/components/AlertBox/AlertBox.mdx
  packages/react-components/src/components/AlertBox/AlertBox.unit.spec.jsx
  packages/react-components/src/components/Checkbox/Checkbox.jsx
  packages/react-components/src/components/Checkbox/Checkbox.mdx
  packages/react-components/src/components/Checkbox/Checkbox.unit.spec.jsx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.jsx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.mdx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.unit.spec.jsx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.jsx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.mdx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.unit.spec.jsx
  packages/react-components/src/components/OMBInfo/OMBInfo.jsx
  packages/react-components/src/components/OMBInfo/OMBInfo.mdx
  packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/additional-docs.js
Labels: major

#909 va-pagination: Change 3 period characters to ellipses character
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#915 OMBInfo: Remove deprecated React component
  packages/core/package.json
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/OMBInfo/OMBInfo.jsx
  packages/react-components/src/components/OMBInfo/OMBInfo.mdx
  packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#916 va-pagination add aria-current label
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#917 Checkbox: Remove deprecated React component
  packages/core/package.json
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/Checkbox/Checkbox.jsx
  packages/react-components/src/components/Checkbox/Checkbox.mdx
  packages/react-components/src/components/Checkbox/Checkbox.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#910 update search script to support uswds query
  packages/design-system-dashboard-cli/README.md
  packages/design-system-dashboard-cli/src/find-ds-components.js
  packages/design-system-dashboard-cli/src/search-files.js
Labels: ignore-for-release

#918 LoadingIndicator: Remove deprecated React component
  packages/core/package.json
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.jsx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.mdx
  packages/react-components/src/components/LoadingIndicator/LoadingIndicator.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#920 AlertBox and MaintenanceBanner: Remove deprecated React components
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/AlertBox/AlertBox.jsx
  packages/react-components/src/components/AlertBox/AlertBox.mdx
  packages/react-components/src/components/AlertBox/AlertBox.unit.spec.jsx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.jsx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.mdx
  packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#846 Add Minimal header component
  packages/storybook/stories/va-crisis-line-modal.stories.jsx
  packages/storybook/stories/va-minimal-header.stories.jsx
  packages/storybook/stories/va-modal-uswds.stories.jsx
  packages/storybook/stories/va-modal.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/assets/VCL-icon-white.svg
  packages/web-components/src/assets/arrow-right-white.svg
  packages/web-components/src/assets/va-seal.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-crisis-line-modal/test/va-crisis-line-modal.e2e.ts
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.scss
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.tsx
  packages/web-components/src/components/va-minimal-header/test/va-minimal-header.e2e.ts
  packages/web-components/src/components/va-minimal-header/test/va-minimal-header.spec.tsx
  packages/web-components/src/components/va-minimal-header/va-minimal-header.scss
  packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx
  packages/web-components/src/contacts.ts
  packages/web-components/stencil.config.ts
  yarn.lock
Labels: minor

#921 Build index.d.ts files
  packages/core/package.json
  packages/core/webpack.config.js
  packages/web-components/package.json
  packages/web-components/tsconfig.json
Labels: patch

#924 va-process-list: accessibility updates (staging review)
  packages/storybook/stories/va-process-list-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-process-list/va-process-list-item.tsx
  packages/web-components/src/components/va-process-list/va-process-list.scss
Labels: patch

#919 sprite.svg file fix
  .github/workflows/publish-storybook.yml
  packages/storybook/.storybook/main.js
Labels: ignore-for-release

#928 1977 icon fix
  .github/workflows/publish-storybook.yml
Labels: ignore-for-release

#929 core version bump for the release
  packages/core/package.json
Labels: ignore-for-release

#930 update core version bump to v31.0.0
  packages/core/package.json
Labels: ignore-for-release

#927 Mc 2517 sql query update
  packages/design-system-dashboard-cli/src/find-ds-components.js
Labels: ignore-for-release

#932 va-alert: force status to be defined
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: minor
