Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-04, with the labels that each got.

#668 Remove the SystemDownView React component
  packages/core/package.json
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/SystemDownView/SystemDownView.jsx
  packages/react-components/src/components/SystemDownView/SystemDownView.mdx
  packages/react-components/src/components/SystemDownView/SystemDownView.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/SystemDownView.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: major

#669 Add va-number-input USWDS v3 variation
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
Labels: minor

#671 1673 button pair responsive bug
  packages/web-components/package.json
  packages/web-components/src/components/va-button-pair/va-button-pair.scss
Labels: patch

#666 1606 va-memorable-date update styles
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#677 add aria-controls and aria-expanded to expand/collapse all button
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#675 Add va-modal USWDS v3 variation
  packages/storybook/stories/va-modal-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: minor

#672 Automate Undeprecated Component Usage Data
  .gitignore
  packages/design-system-dashboard-cli/README.md
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/package.json
  packages/design-system-dashboard-cli/src/codeowners.json
  packages/design-system-dashboard-cli/src/find-ds-components.js
  packages/design-system-dashboard-cli/src/update-repos.js
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/design-system-dashboard-cli/test/write-react-owners-to-csv.spec.js
  update-component-usage.sh
  yarn.lock
Labels: ignore-for-release

#681 Dispose of loading indicator observer - 1664
  .yarn/versions/916472c4.yml
  packages/core/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
Labels: patch

#683 Bumping core for release
  packages/core/package.json
Labels: minor

#680 Reassigning a few apps to facilities
  packages/design-system-dashboard-cli/src/codeowners.json
Labels: ignore-for-release

#679 1679 Add icon support to va-accordion-item
  README.md
  packages/core/package.json
  packages/storybook/.storybook/style.scss
  packages/storybook/stories/va-accordion.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.css
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: minor

#678 Add va-privacy-agreement USWDS v3 variation
  packages/storybook/stories/va-privacy-agreement-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: minor

#684 (bug) fixed styling issue for sub header
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.css
Labels: patch

#682 add tile variation of checkbox to storybook
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
Labels: patch

#687 Remove deprecated ProgressButton React component
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/ProgressButton/ProgressButton.jsx
  packages/react-components/src/components/ProgressButton/ProgressButton.mdx
  packages/react-components/src/components/ProgressButton/ProgressButton.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#686 Remove DropDownPanel
  packages/core/package.json
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/src/components/DropDownPanel/DropDownPanel.jsx
  packages/react-components/src/components/DropDownPanel/DropDownPanel.mdx
  packages/react-components/src/components/DropDownPanel/DropDownPanel.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/DropDownPanel.stories.jsx
Labels: major
