Repository department-of-veterans-affairs/component-library, pull requests merged in 2023-03, with the labels that each got.

#635 Adding additional checklist items to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#634 Mitigate Radio and Radio Option Formation Problems
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/global/_variables.scss
Labels: patch

#636 Mitigate Select component Formation problems
  packages/storybook/.storybook/style.scss
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/global/_formation_overrides.scss
Labels: patch

#641 Adding Storybook v3 override styles
  packages/storybook/.storybook/style.scss
Labels: ignore-for-release

#642 Update va-button states to match Sketch
  packages/web-components/package.json
  packages/web-components/src/components/va-button/va-button.css
  packages/web-components/src/global/_settings.scss
  packages/web-components/src/global/variables.css
  packages/web-components/src/mixins/focusable.css
Labels: patch

#644 Update Formation to v7.0.5
  packages/react-components/package.json
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: patch

#638 Removing Formation overrides from storybook
  packages/storybook/.storybook/preview.js
Labels: ignore-for-release

#643 va-button: Update the secondary hover color
  packages/web-components/package.json
  packages/web-components/src/components/va-button/va-button.css
Labels: patch

#645 va-button: Add USWDS v3 variation
  packages/core/package.json
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/mixins/focusable.css
Labels: minor

#650 Remove RadioButtons React component from component library
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/RadioButtons/RadioButtons.jsx
  packages/react-components/src/components/RadioButtons/RadioButtons.mdx
  packages/react-components/src/components/RadioButtons/RadioButtons.unit.spec.jsx
  packages/react-components/src/index.js
Labels: major

#653 Bump core version to v14.0.0
  packages/core/package.json
Labels: ignore-for-release

#656 Add analytics to va-search-input
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: patch

#657 Adds a Need help? component. [Amends #1467]
  packages/core/package.json
  packages/storybook/stories/va-need-help.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-need-help/test/va-need-help.e2e.ts
  packages/web-components/src/components/va-need-help/va-need-help.css
  packages/web-components/src/components/va-need-help/va-need-help.tsx
Labels: minor

#659 Fixed the missing code in Featured content
  packages/storybook/stories/va-featured-content.stories.jsx
Labels: bug, minor

#660 Fixes code example for need help component. [Amends #1467]
  packages/core/package.json
  packages/storybook/stories/va-need-help.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-need-help/va-need-help.tsx
Labels: bug, minor

#661 Update to codeql v2
  .github/workflows/codeql.yml
Labels: ignore-for-release

#658 Add va-button-pair USWDS v3 variation
  packages/storybook/stories/va-button-pair-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.css
  packages/web-components/src/components/va-button-pair/va-button-pair.scss
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: minor

#662 Add yarn watch:stencil to build steps
  README.md
Labels: ignore-for-release

#663 Move all react components to deprecated section
  packages/storybook/stories/DropDownPanel.stories.jsx
  packages/storybook/stories/ExpandingGroup.stories.jsx
  packages/storybook/stories/OMBInfo.stories.jsx
  packages/storybook/stories/SystemDownView.stories.jsx
  packages/storybook/stories/additional-docs.js
  packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
Labels: minor

#665 1488 memorable date error translate
  packages/web-components/package.json
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#667 Fix maturity scale icons for deprecated React components
  packages/storybook/stories/DropDownPanel.stories.jsx
  packages/storybook/stories/ExpandingGroup.stories.jsx
  packages/storybook/stories/SystemDownView.stories.jsx
  packages/storybook/stories/additional-docs.js
Labels: ignore-for-release
