Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-04, with the labels that each got.

#1104 CSS-Library: Adding mobile-medium breakpoint and replacing medium-screen with 768px
  .github/workflows/require-label.yml
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/breakpoints.json
Labels: css-library

#1105 va-select: Add aria-describedby-message for screen readers
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
Labels: patch

#1106 Add pre-commit script for checking branch name
  .husky/pre-commit
  package.json
  yarn.lock
Labels: ignore-for-release

#1108 skip chromatic if user is depdendabot
  .github/workflows/chromatic-link.yml
  .github/workflows/chromatic.yml
Labels: ignore-for-release

#1110 skip chromatic on dependabot branches
  .github/workflows/chromatic.yml
Labels: ignore-for-release

#1117 va-icon: Updating va-icon icon sprite sheet with new icons
  packages/storybook/public/assets/sprite.svg
  packages/storybook/stories/va-icon-uswds.stories.jsx
  packages/web-components/src/assets/sprite.svg
Labels: patch

#1118 Bumping versions to reflect latest release
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1119 Rename medium-mobile breakpoint to tablet
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/breakpoints.json
Labels: css-library

#1120 Update branch name check regex
  .husky/pre-commit
Labels: ignore-for-release

#1116 Core release v39.0.0 + va-memorable-date: remove non-USWDS version
  packages/core/package.json
  packages/storybook/stories/va-memorable-date.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: major

#1123 CSS Library: Fix build issues
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/elements.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
Labels: css-library

#1122 Check for isTouched before opening search suggestions
  packages/web-components/package.json
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: patch

#1130 react-output-target version number update
  packages/web-components/package.json
  yarn.lock
Labels: patch

#1132 Bump core to 39.0.1
  packages/core/package.json
Labels: ignore-for-release

#1131 va-button-icon: Adding new va-button-icon component
  packages/storybook/stories/va-button-icon.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-icon/test/va-button-icon.e2e.ts
  packages/web-components/src/components/va-button-icon/va-button-icon.scss
  packages/web-components/src/components/va-button-icon/va-button-icon.tsx
Labels: minor

#1112 Multiple Components: Removing Font Awesome icons in favor of va-icon in V3 Components
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-crisis-line-modal/test/va-crisis-line-modal.e2e.ts
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.scss
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.tsx
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.tsx
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.scss
  packages/web-components/src/components/va-search-input/va-search-input.tsx
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
  packages/web-components/src/global/_formation_overrides.scss
Labels: patch

#1127 Fix va-icon svg path to work in prod and dev environs, take 2
  packages/core/webpack.config.js
  packages/storybook/public/img/sprite.svg
  packages/web-components/package.json
  packages/web-components/src/components/va-icon/va-icon.tsx
  packages/web-components/src/img/sprite.svg
  packages/web-components/stencil.config.ts
Labels: bug, minor

#1133 Fix to va-icon position for va-alert "continue" status
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/va-alert.scss
Labels: patch

#1128 va-table: adding USWDS borderless variation
  packages/storybook/stories/va-table-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table-inner/va-table-row.css
  packages/web-components/src/components/va-table/va-table-inner/va-table-row.tsx
  packages/web-components/src/components/va-table/va-table-inner/va-table-slot.css
  packages/web-components/src/components/va-table/va-table.scss
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/global/main.css
Labels: minor

#1136 Major version bump to v40
  packages/core/package.json
Labels: ignore-for-release

#1135 Update VaFileInput so the VaChange event target.value gets reset
  packages/web-components/package.json
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1139 Add message-aria-describedby to button
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
Labels: minor
