Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-09, with the labels that each got.

#1309 web-components: remove remaining references to uswds variation
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-maintenance-banner/test/va-maintenance-banner.e2e.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/mixins/focusable.css
  packages/web-components/src/mixins/form-field-error.css
  packages/web-components/src/mixins/uswds-error-border.scss
  packages/web-components/src/mixins/uswds-input-width.scss
  packages/web-components/src/utils/utils.ts
Labels: patch

#1312 update versions
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1304 Stencil v4 upgrade
  packages/storybook/package.json
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
  packages/web-components/src/components/va-promo-banner/test/va-promo-banner.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/stencil.config.ts
  yarn.lock
Labels: minor

#1315 CSS Library: add new breakpoints
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/_uswds-theme.scss
  packages/web-components/package.json
  yarn.lock
Labels: css-library

#1316 va-search-input: add back type ahead dropdown style
  packages/web-components/src/components/va-search-input/va-search-input.scss
Labels: patch

#1318 CSS Library: remove grid classes
  packages/core/package.json
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/utilities/_index.scss
  packages/web-components/package.json
  yarn.lock
Labels: css-library

#1317 CSS Library: Add mobile forms surface tokens
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/utils.css.map
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/table.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/shame.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
Labels: css-library

#1305 fix: focus outline color fix for v3 components
  packages/web-components/src/components/va-back-to-top/va-back-to-top.css
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-promo-banner/va-promo-banner.css
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/global/main.css
Labels: patch

#1322 CSS Library: add hub-records color utility classes
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/tokens/color.scss
Labels: css-library

#1321 va-link-action: Adding an aria label prop
  packages/storybook/stories/va-link-action.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link-action/test/va-link-action.e2e.ts
  packages/web-components/src/components/va-link-action/va-link-action.tsx
Labels: minor

#1324 CSS Library: Remove progress-box padding
  packages/css-library/dist/stylesheets/modules/m-omb-info.css
  packages/css-library/dist/stylesheets/modules/m-omb-info.css.map
  packages/css-library/dist/stylesheets/shame.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/modules/m-omb-info.scss
  packages/css-library/src/stylesheets/shame.scss
Labels: css-library

#1325 CSS Library: update breakpoint names and adjust `small-desktop-screen` value
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/utils.css.map
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/core/base.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/labels.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/table.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/modules/m-additional-info.css.map
  packages/css-library/dist/stylesheets/modules/m-alert.css.map
  packages/css-library/dist/stylesheets/modules/m-breadcrumbs.css.map
  packages/css-library/dist/stylesheets/modules/m-dropdown.css.map
  packages/css-library/dist/stylesheets/modules/m-form-process.css.map
  packages/css-library/dist/stylesheets/modules/m-homepage-hero.css.map
  packages/css-library/dist/stylesheets/modules/m-hub-page-link-list.css.map
  packages/css-library/dist/stylesheets/modules/m-megamenu.css
  packages/css-library/dist/stylesheets/modules/m-megamenu.css.map
  packages/css-library/dist/stylesheets/modules/m-modal.css.map
  packages/css-library/dist/stylesheets/modules/m-nav-sidebar.css
  packages/css-library/dist/stylesheets/modules/m-nav-sidebar.css.map
  packages/css-library/dist/stylesheets/modules/m-process-list.css.map
  packages/css-library/dist/stylesheets/modules/va-pagination.css.map
  packages/css-library/dist/stylesheets/modules/va-tabs.css.map
  packages/css-library/dist/stylesheets/shame.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/breakpoints.json
Labels: css-library

#1320 va-search-input: don't fire extra submit event on keyboard form submit
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: patch

#1323 va-link: fix double outline on focus
  packages/web-components/src/components/va-link/va-link.scss
Labels: patch

#1330 Remove props from disabled checkbox/radio stories
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/storybook/stories/va-radio-uswds.stories.jsx
Labels: ignore-for-release

#1328 Clean up text in va-file-input-multiple story
  packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
Labels: ignore-for-release

#1327 va-checkbox-group: add message-aria-describedby prop
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
Labels: minor

#1329 va-checkbox & va-radio-option: Remove option-label
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
Labels: patch

#1326 va-file-input: Focus on delete after closing modal
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1331 va-checkbox: Fix description slot
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#1314 compose va mobile team's storybook with dst storybook
  packages/storybook/.storybook/main.js
Labels: ignore-for-release

#1333 Fix to "margin-x" utilities
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/utilities.scss
Labels: css-library

#1334 CSS Library: Add semantic color tokens
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/tokens/color.scss
  packages/css-library/src/utilities/background-color.scss
  packages/css-library/src/utilities/border.scss
  packages/css-library/src/utilities/color.scss
Labels: css-library

#1335 Version bumps for 46.3.1 release
  package.json
  packages/core/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1336 va-checkbox and va-radio-option: Fix for Voice Control support
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
Labels: patch

#1338 CSS Library: add semantic typography tokens
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/fonts.json
Labels: css-library

#1341 va-accordion: check for open accordion items on load
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#1340 va-select: add support for optgroup markup
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-select/va-select.tsx
Labels: patch

#1342 va-checkbox and va-radio-option: Increasing the max-width to 68ex
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio/va-radio.scss
Labels: patch

#1343 9/26/2024 release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1345 va-textarea: Fixing it so textarea components are resizable again
  packages/web-components/src/components/va-textarea/va-textarea.scss
Labels: patch
