Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-01, with the labels that each got.

#1007 va-checkbox: Add error message styling
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: bug, minor

#1002 2324 - component-library: update colors to USWDS v3
  packages/core/package.json
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/elements.css
  packages/css-library/dist/elements.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/dist/utilities.css
  packages/css-library/package.json
  packages/css-library/src/tokens/color.scss
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
  packages/react-components/package.json
  packages/storybook/.storybook/manager.js
  packages/storybook/package.json
  packages/storybook/stories/styles/va-icon.scss
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/assets/arrow-both.svg
  packages/web-components/src/assets/green-check.svg
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.scss
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/mixins/uswds-error-border.scss
  yarn.lock
Labels: major

#1008 va-textarea: add new form pattern support
  packages/storybook/stories/va-textarea-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: minor

#1011 Add ARIA label to featured content region
  packages/web-components/src/components/va-featured-content/test/va-featured-content.e2e.ts
  packages/web-components/src/components/va-featured-content/va-featured-content.tsx
Labels: patch

#1016 [Mobile Design System] Include .json in NPM dist
  packages/css-library/package.json
Labels: minor

#1018 update core to 34.1.0 and css-library to 0.3.0
  packages/core/package.json
  packages/css-library/package.json
  yarn.lock
Labels: ignore-for-release

#1014 va-memorable-date: make month default to input instead of select
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#1023 update formation@10.1.2
  packages/react-components/package.json
  packages/storybook/package.json
  packages/web-components/package.json
  yarn.lock
Labels: patch

#1020 va-banner: Set data-role to 'region' and create property data-label to set aria-label on first div child of nested va-alert
  packages/storybook/stories/va-banner.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: minor

#1026 Update references for testing single components in readme
  README.md
Labels: ignore-for-release

#1028 va-checkbox-group, va-radio - move hint to legend
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: patch

#1029 va-card: add prop to display a gray background
  packages/storybook/stories/va-card.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-card/test/va-card.e2e.ts
  packages/web-components/src/components/va-card/va-card.scss
  packages/web-components/src/components/va-card/va-card.tsx
  packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
Labels: minor

#1032 update core version to v34.2.0 for release
  packages/core/package.json
Labels: ignore-for-release

#1034 va-checkbox-group: add new form pattern support
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: minor

#1033 va-alert: fix close button position on full-width
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/va-alert.scss
Labels: patch

#1035 va-alert: remove background only variation for USWDS v3
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: minor

#1017 va-file-input: Adding a V3-compatible (USWDS) version
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input-upgrader.ts
  packages/web-components/src/components/va-file-input/va-file-input.css
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/utils/utils.ts
Labels: major

#1025 va-text-input: Deprecating Max Length variation for V3
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1009 va-radio: add new form pattern support
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: minor

#1037 va-header-minimal: Update Storybook Link and Rename va-header-minimal Component
  packages/storybook/stories/va-header-minimal.stories.jsx
  packages/storybook/stories/va-minimal-header.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-header-minimal/test/va-header-minimal.e2e.ts
  packages/web-components/src/components/va-header-minimal/test/va-header-minimal.spec.tsx
  packages/web-components/src/components/va-header-minimal/va-header-minimal.scss
  packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx
Labels: major

#1041 cleanup: auto generated component type changes
  packages/web-components/src/components.d.ts
Labels: patch

#1040 va-radio: set display to block for .usa-hint class
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: patch

#1039 V3 Colors: add missing colors to css variable exports
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/elements.css
  packages/css-library/dist/elements.css.map
  packages/css-library/dist/fonts.css
  packages/css-library/dist/print.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/dist/utilities.css
  packages/css-library/package.json
  packages/css-library/src/tokens/color.scss
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
  packages/web-components/package.json
  yarn.lock
Labels: patch
