Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-08, with the labels that each got.

#1240 va-textarea: remove v1
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: major

#1243 Update README.md
  README.md
  packages/web-components/readme.md
Labels: ignore-for-release

#1249 va-accordion: remove v1 variation
  packages/web-components/src/assets/minus.svg
  packages/web-components/src/assets/plus.svg
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.scss
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: major

#1250 va-file-input/multiple: add aria-hidden to file thumbnails
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1251 va-breadcrumb: mobile view padding fix
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
Labels: patch

#1252 va-file-input | story: replace 'Label Header' with 'Header label'
  packages/storybook/stories/va-file-input-uswds.stories.jsx
Labels: ignore-for-release

#1254 version bump 8/5/24
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1253 Tool for getting codeowner team member names
  codeowner-scan.sh
Labels: ignore-for-release

#1256 va-text-input: add autofill Safari documentation to storybook
  packages/storybook/stories/va-text-input-uswds.stories.jsx
Labels: patch

#1255 va-statement-of-truth: reflect error prop in va-text-input for styling
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#1258 va-select: remove v1 variation
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-select/va-select.tsx
Labels: major

#1260 va-radio, va-radio-option: v1 variation code removal
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: major

#1262 va-date:v1 code cleanup
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-date/va-date.tsx
Labels: patch

#1265 va-breadcrumbs: remove v1 code
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: minor

#1264 va-checkbox, va-checkbox-group, va-privacy-agreement: v1 variation code removal
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.tsx
Labels: major

#1263 CSS Library: generate medium-screen breakpoint utility classes
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/src/utilities/border.scss
  packages/css-library/src/utilities/flex-grid.scss
Labels: css-library

#1257 va-search-input: Add disableAnalytics check for submit and blur callbacks
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: patch

#1267 va-back-to-top: set display none to link when it should not be visible
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/web-components/src/components/va-back-to-top/va-back-to-top.css
Labels: patch

#1270 va-segmented-progress-bar: v1 variation code removal
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.scss
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: major

#1272 va-additional-info: v1 variation removal
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
Labels: major

#1273 va-pagination: remove v1 code
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.scss
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: major

#1274 va-summary-box: v1 variation code removal
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-summary-box/test/va-summary-box.e2e.ts
  packages/web-components/src/components/va-summary-box/va-summary-box.scss
  packages/web-components/src/components/va-summary-box/va-summary-box.tsx
Labels: major

#1275 va-button & va-button-pair: Removing V1 code
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.scss
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/components/va-omb-info/test/va-omb-info.e2e.ts
  packages/web-components/src/components/va-omb-info/va-omb-info.css
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
Labels: major

#1276 va-process-list: v1 variation removal
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-process-list/test/va-process-list.e2e.ts
  packages/web-components/src/components/va-process-list/va-process-list.scss
  packages/web-components/src/components/va-process-list/va-process-list.tsx
Labels: major

#1277 va-file-input/va-file-input-multiple: v1 variation removal
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: major

#1278 va-search-input: remove v1 code
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
  packages/web-components/src/components/va-search-input/va-search-input.scss
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: minor

#1268 va-alert and va-banner: remove v1 code
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert-slot.css
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: major

#1280 va-text-input: add suffix icon support
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1283 version bump for release
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1281 va-text-input: add step prop for decimal support
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1269 Add external link to va-link
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.scss
  packages/web-components/src/components/va-link/va-link.tsx
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-number-input/va-number-input.tsx
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
Labels: minor

#1284 va-number-input: Component removal
  packages/storybook/stories/va-number-input-uswds.stories.jsx
  packages/storybook/stories/va-number-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-number-input/va-number-input.tsx
Labels: major

#1287 CSS Library: Fix medium-screen utility generator so that it handles multiple properties
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/utilities.scss
Labels: css-library

#1271 va-table: remove v1 code
  packages/storybook/stories/va-table.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table.tsx
Labels: major

#1290 update web-components to always use configured instance of i18n
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/index.ts
Labels: minor

#1292 va-file-input-multiple: Filter out empty file from emitted files
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
Labels: minor

#1279 Update va-text-input to fix va-date and va-memorable-date error state
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1293 Revert "update web-components to always use configured instance of i1…
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/index.ts
Labels: minor

#1288 va-link: "Back" variant
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.scss
  packages/web-components/src/components/va-link/va-link.tsx
Labels: minor

#1296 va-radio: re-add mixins
  packages/web-components/src/components/va-radio/va-radio.scss
Labels: patch

#1291 web-components: stencil@v3
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/storybook/stories/wc-helpers.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-banner/test/va-banner.spec.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/stencil.config.ts
  yarn.lock
Labels: minor

#1157 Change bg to background in semantic token
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/color.json
Labels: css-library

#1294 va-button-pair: add support for custom button text
  packages/storybook/stories/va-button-pair-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
Labels: minor

#1297 web-components: adjust i18n config
  packages/web-components/src/components/va-accordion/va-accordion.tsx
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/index.ts
  packages/web-components/tsconfig.bindings.json
Labels: minor

#1299 bump version numbers
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1301 patch bump
  packages/core/package.json
Labels: ignore-for-release

#1303 Add messageAriaDescribedby to va-radio
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: minor

#1307 va-link: re-add font inherit
  packages/core/package.json
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-link/va-link.scss
Labels: patch

#1310 css-library: add important! for utilities
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/_uswds-theme.scss
  packages/css-library/src/stylesheets/utilities.scss
Labels: minor

#1308 va-select: add width prop to set width of select element
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-select/va-select.tsx
Labels: minor
