Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-10, with the labels that each got.

#1347 va-header-minimal: default to headingless
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-header-minimal/test/va-header-minimal.spec.tsx
  packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx
Labels: major

#1351 update version numbers
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1346 va-on-this-page: Rewrite to use ul instead of dl for list of links
  packages/web-components/src/components/va-on-this-page/test/va-on-this-page.e2e.ts
  packages/web-components/src/components/va-on-this-page/va-on-this-page.css
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
Labels: minor

#1352 css-library: update margin auto value
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/tokens/margin.scss
Labels: css-library

#1354 CSS Library: update font-family utility map base name
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/utilities/font.scss
Labels: css-library

#1355 update version for core and web-components
  packages/core/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1357 va-modal: set box-sizing to border-box to prevent text overflow
  packages/web-components/src/components/va-modal/va-modal.scss
Labels: patch

#1363 Open accordion when media is print
  packages/storybook/stories/va-accordion-uswds.stories.jsx
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
  packages/web-components/stencil.config.ts
Labels: patch

#1360 va-link: add router link Storybook example
  .github/workflows/chromatic.yml
  packages/storybook/stories/va-link.stories.jsx
Labels: ignore-for-release

#1362 va-process-list-item: Add text to describe status
  packages/web-components/package.json
  packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-process-list/va-process-list-item.tsx
  yarn.lock
Labels: minor

#1365 3274 process list accessibility
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
Labels: patch

#1366 Toggle the onlyChanged Chromatic setting for a new UI baseline
  README.md
Labels: ignore-for-release

#1368 va-process-list: change color variable from usa to vads
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
Labels: patch

#1367 Add custom message to va-file-input and update message in va-file-input-multiple
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1364 va-table: show table header for non-stacked & stacked small screen
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
Labels: patch

#1361 Add Prefill Pattern Components to Storybook
  packages/storybook/stories/pattern-prefill/va-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-alert-with-editable-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-alert.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-signed-in.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefilled-info-with-uneditable-card.stories.jsx
  packages/storybook/stories/va-alert-uswds.stories.jsx
Labels: ignore-for-release

#1358 Sortable table
  packages/storybook/stories/va-table-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/sort/alpha.tsx
  packages/web-components/src/components/va-table/sort/date.tsx
  packages/web-components/src/components/va-table/sort/numerical.tsx
  packages/web-components/src/components/va-table/sort/utils.tsx
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/utils/constants.ts
Labels: major

#1371 CSS Library: replace FA icons for action link and alert classes
  packages/css-library/dist/img/alerts/error.svg
  packages/css-library/dist/img/alerts/info.svg
  packages/css-library/dist/img/alerts/success.svg
  packages/css-library/dist/img/alerts/warning.svg
  packages/css-library/dist/img/arrow-right.svg
  packages/css-library/dist/stylesheets/modules/m-action-link.css
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/modules/m-alert.css
  packages/css-library/dist/stylesheets/modules/m-alert.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/assets/img/alerts/error.svg
  packages/css-library/src/assets/img/alerts/info.svg
  packages/css-library/src/assets/img/alerts/success.svg
  packages/css-library/src/assets/img/alerts/warning.svg
  packages/css-library/src/assets/img/arrow-right.svg
  packages/css-library/src/stylesheets/modules/m-action-link.scss
  packages/css-library/src/stylesheets/modules/m-alert.scss
  packages/storybook/stories/action-link.stories.mdx
Labels: css-library

#1370 va-table: update va-table-inner to properly scope table header row to columns
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
Labels: patch

#1374 Bump version numbers for 47.2.0 release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1300 va-file-input: add support for read-only mode
  packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.scss
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1376 va-select: add import for focusable mixin
  packages/web-components/src/components/va-select/va-select.scss
Labels: patch

#1372 va-modal: set overflow-wrap:anywhere on modal content
  packages/web-components/src/components/va-modal/va-modal.scss
Labels: patch

#1378 CSS Library: style and image path updates for alert and action link modules
  packages/css-library/dist/img/error.svg
  packages/css-library/dist/img/info.svg
  packages/css-library/dist/img/success.svg
  packages/css-library/dist/img/warning.svg
  packages/css-library/dist/stylesheets/modules/m-action-link.css
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/modules/m-alert.css
  packages/css-library/dist/stylesheets/modules/m-alert.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/assets/img/error.svg
  packages/css-library/src/assets/img/info.svg
  packages/css-library/src/assets/img/success.svg
  packages/css-library/src/assets/img/warning.svg
  packages/css-library/src/stylesheets/modules/m-action-link.scss
  packages/css-library/src/stylesheets/modules/m-alert.scss
Labels: css-library

#1377 va-date: add prop to make month optional
  packages/storybook/stories/va-date.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: minor

#1381 CSS Library: remove the /alerts image path
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/modules/m-alert.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/formation-overrides/components/_alerts.scss
  packages/css-library/src/stylesheets/modules/m-alert.scss
Labels: css-library

#1380 focusable: add tabindex selector
  packages/web-components/src/mixins/focusable.css
Labels: patch

#1383 update package versions for release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release
