Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-05, with the labels that each got.

#1121 removed modal v1 component and storybook
  packages/core/package.json
  packages/storybook/stories/va-modal.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
Labels: major

#1140 Sweeping fixes to va-icon and buttons that use icons
  packages/web-components/package.json
  packages/web-components/src/components/va-button-icon/va-button-icon.scss
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-icon/va-icon.scss
Labels: patch

#1141 2602 - Reverse va-link color
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/va-link.css
  packages/web-components/src/components/va-link/va-link.tsx
Labels: minor

#1145 va-link: Add destination and origin to analytics details
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.tsx
Labels: patch

#1147 va-statment-of-truth: make event payloads easier to use
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
Labels: patch

#1151 update core to 41.1.0
  packages/core/package.json
Labels: ignore-for-release

#1150 Remove non-USWDS Storybook stories
  packages/storybook/stories/va-accordion.stories.jsx
  packages/storybook/stories/va-additional-info.stories.jsx
  packages/storybook/stories/va-alert.stories.jsx
  packages/storybook/stories/va-breadcrumbs.stories.jsx
  packages/storybook/stories/va-button-pair.stories.jsx
  packages/storybook/stories/va-button.stories.jsx
  packages/storybook/stories/va-checkbox-group.stories.jsx
  packages/storybook/stories/va-checkbox.stories.jsx
  packages/storybook/stories/va-pagination.stories.jsx
  packages/storybook/stories/va-privacy-agreement.stories.jsx
  packages/storybook/stories/va-process-list.stories.jsx
  packages/storybook/stories/va-radio.stories.jsx
  packages/storybook/stories/va-search-input.stories.jsx
  packages/storybook/stories/va-segmented-progress-bar.stories.jsx
  packages/storybook/stories/va-select.stories.jsx
  packages/storybook/stories/va-statement-of-truth-uswds.stories.jsx
  packages/storybook/stories/va-summary-box.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/storybook/stories/va-textarea.stories.jsx
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
Labels: ignore-for-release

#1114 Add semantic tokens and update USWDS color filters for VA Mobile
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/tokens/color.json
Labels: css-library

#1148 va-text-input: Prevent adding invalid ID to aria-describedby
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#1153 va-accordion: add duplicate print media to unhide print content
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
Labels: patch

#1155 va-icon: Adding Pill icon to sprite sheet
  packages/storybook/public/img/sprite.svg
  packages/storybook/stories/va-icon-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/assets/sprite.svg
Labels: patch

#1158 va-text-input: address validation bug for currency / valid range
  packages/web-components/package.json
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: patch

#1142 2642 file input update
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1156 button-icon: color contrast updates for destructive button
  packages/web-components/package.json
  packages/web-components/src/components/va-button-icon/va-button-icon.scss
Labels: patch

#1160 Fixes line-height on va-file-input
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: bug, minor

#1161 bump core to 42.1.0
  packages/core/package.json
Labels: minor

#1163 CSS Library: add yarn.lock file to package
  packages/css-library/.gitignore
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/package.json
  packages/css-library/yarn.lock
Labels: ignore-for-release

#1165 va-icon: Fixing pill icon's hard-coded fill
  packages/storybook/public/assets/sprite.svg
  packages/storybook/public/img/sprite.svg
  packages/web-components/package.json
  packages/web-components/src/assets/sprite.svg
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.tsx
  packages/web-components/src/img/sprite.svg
  packages/web-components/stencil.config.ts
Labels: patch

#1162 va-file-input: text wrapping
  packages/web-components/src/components/va-file-input/va-file-input.scss
Labels: patch

#1166 CSS Library: add USWDS typography stylesheet for Source Sans Pro content
  packages/css-library/dist/uswds-typography.css
  packages/css-library/dist/uswds-typography.css.map
  packages/css-library/dist/utilities.css
  packages/css-library/dist/utilities.css.map
  packages/css-library/package.json
  packages/css-library/src/stylesheets/_core.scss
  packages/css-library/src/stylesheets/_elements.scss
  packages/css-library/src/stylesheets/_uswds-theme.scss
  packages/css-library/src/stylesheets/base/_va.scss
  packages/css-library/src/stylesheets/formation-overrides/elements/_typography.scss
  packages/css-library/src/stylesheets/modules/_m-breadcrumbs.scss
  packages/css-library/src/stylesheets/uswds-typography.scss
  packages/css-library/src/stylesheets/utilities.scss
  packages/web-components/package.json
  yarn.lock
Labels: css-library

#1170 update core version for release v42.1.1
  packages/core/package.json
Labels: ignore-for-release

#1168 Update va-file-input to handle drag-and-drop restricting files
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components/va-file-input/fileExtensionToMimeType.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1171 add yarn install to publish workflow for css-library
  .github/workflows/publish.yml
Labels: ignore-for-release

#1169 CSS Library: Fixing naming conventions for utility classes.
  packages/css-library/dist/base/headings.css
  packages/css-library/dist/base/headings.css.map
  packages/css-library/dist/full.css
  packages/css-library/dist/full.css.map
  packages/css-library/dist/utilities.css
  packages/css-library/dist/utilities.css.map
  packages/css-library/package.json
  packages/css-library/src/tokens/border.scss
  packages/css-library/src/tokens/padding.scss
  packages/css-library/src/tokens/visibility.scss
  packages/css-library/src/utilities/background-color.scss
  packages/css-library/src/utilities/border.scss
  packages/css-library/src/utilities/color.scss
  packages/css-library/src/utilities/display.scss
  packages/css-library/src/utilities/flex-grid.scss
  packages/css-library/src/utilities/flexbox.scss
  packages/css-library/src/utilities/font.scss
  packages/css-library/src/utilities/height.scss
  packages/css-library/src/utilities/line-height.scss
  packages/css-library/src/utilities/margin.scss
  packages/css-library/src/utilities/measure.scss
  packages/css-library/src/utilities/padding.scss
  packages/css-library/src/utilities/position.scss
  packages/css-library/src/utilities/text-align.scss
  packages/css-library/src/utilities/text-decoration.scss
  packages/css-library/src/utilities/visibility.scss
  packages/css-library/src/utilities/width.scss
Labels: minor, css-library
