Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-12, with the labels that each got.

#1421 va-alert: add full width functionality
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch

#1423 48.1.1 update versions
  packages/core/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1422 va-process-list: add ability to customize eyebrow status text
  packages/storybook/stories/va-process-list-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
  packages/web-components/src/components/va-process-list/va-process-list-item.tsx
Labels: minor

#1373 va-combo-box: add new component
  packages/storybook/stories/va-combo-box-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
  packages/web-components/src/components/va-combo-box/va-combo-box.scss
  packages/web-components/src/components/va-combo-box/va-combo-box.tsx
Labels: minor

#1400 PATCH: Remove aria-controls and aria-expanded from `va-accordion` expand all button
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#1429 Moving i18n files to .mjs / Node 20 upgrade
  .github/workflows/chromatic.yml
  .github/workflows/node.js.yml
  .github/workflows/publish-storybook.yml
  .github/workflows/publish.yml
  packages/core/src/i18n/i18n-setup.mjs
  packages/core/src/i18n/language-detector.mjs
  packages/core/src/i18n/translations/en.mjs
  packages/core/src/i18n/translations/es.mjs
  packages/core/src/i18n/translations/tl.mjs
  packages/react-components/index.js
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.spec.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/index.ts
Labels: ignore-for-release

#1426 va-checkbox: add indeterminate prop
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: minor

#1432 Add address block to CSS library
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/base/va.scss
Labels: css-library

#1431 va-table: Parse html to plain string before setting it to CSS content
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
Labels: patch

#1424 New va-alert-sign-in component
  packages/storybook/stories/va-alert-sign-in.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert-sign-in/AlertSignInVariants.ts
  packages/web-components/src/components/va-alert-sign-in/test/va-alert-sign-in.e2e.ts
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.scss
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx
Labels: minor

#1434 va-language-toggle: Add label text to event, remove va-link analytics
  packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
  packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx
Labels: patch

#1435 Update versions for release 48.2.0
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1436 Update README with release changes and contribution clarifications
  README.md
Labels: ignore-for-release

#1438 va-alert-sign-in: Modifying headline to use rems
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.scss
Labels: patch

#1437 va-process-list-item: move status eyebrow into header so that it gets read by screen readers
  packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
  packages/web-components/src/components/va-process-list/test/va-process-list.e2e.ts
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-process-list/va-process-list-item.tsx
Labels: patch

#1439 va-table: add striped variation
  packages/storybook/stories/va-table-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table.tsx
Labels: minor

#1433 Fix va-table screen reader not announcing sort
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
Labels: patch

#1440 va-file-input-multiple: Fix multiple emits of vaMultipleChange
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1443 12-19-24 Core and Web-C Version Bumps
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release
