Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-07, with the labels that each got.

#1209 Add css and tests to FA icon search
  packages/design-system-dashboard-cli/src/create-spreadsheets.js
  packages/design-system-dashboard-cli/src/search-files.js
  packages/design-system-dashboard-cli/src/write-comp-usage-to-csv.js
Labels: ignore-for-release

#1204 Add stacked table variant
  packages/storybook/stories/va-table-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table.tsx
Labels: minor

#1213 Add override to header margin on adjacent selector
  packages/web-components/package.json
  packages/web-components/src/mixins/headers.css
Labels: patch

#1216 va-search-input: fix suggestion box from always staying open
  packages/web-components/package.json
  packages/web-components/src/components/va-search-input/va-search-input.tsx
Labels: patch

#1218 va-file-input: Update modal title
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1217 va-text-input: New prefix and suffix variant
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1220 va-telephone: remove number formatting from aria-label
  packages/web-components/package.json
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: patch

#1222 va-link: add style inheritance to anchor element
  packages/web-components/package.json
  packages/web-components/src/components/va-link/va-link.css
Labels: patch

#1223 update core to 43.0.0
  packages/core/package.json
Labels: ignore-for-release

#1221 Align error alert with other statuses
  packages/storybook/stories/va-alert-uswds.stories.jsx
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
Labels: patch

#1224 Update readme with more versioning examples
  README.md
Labels: ignore-for-release

#1225 va-promo-banner: Renaming localstorage key var name
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: patch

#1226 va-file-input-multiple accessibility fixes
  packages/web-components/package.json
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#1229 Add class to file input labels to fix text resizing
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.scss
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1230 va-memorable-date: remove "Please" from hint text
  packages/core/src/i18n/translations/en.js
  packages/web-components/package.json
Labels: patch

#1231 Update core version for release - v43.01
  packages/core/package.json
Labels: ignore-for-release

#1234 Storybook example improvements
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/storybook/stories/va-process-list-uswds.stories.jsx
Labels: ignore-for-release

#1232 va-textarea: add support for formHeadingLevel prop
  packages/storybook/stories/va-textarea-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#1228 va-file-input: update screen reader message when file is uploaded or removed
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1235 va-accordion: replace icon with va-icon in storybook
  packages/storybook/stories/va-accordion-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
Labels: patch

#1238 Chromatic Turbosnap: turn back on the onlyChanged flag
  .github/workflows/chromatic.yml
Labels: ignore-for-release

#1227 va-breadcrumbs: Updating language support for breadcrumbs
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: patch

#1239 va-text-input: add icon and suffix story
  packages/storybook/stories/va-text-input-uswds.stories.jsx
Labels: patch

#1237 Update USWDS package to v3.8.1
  packages/css-library/package.json
  packages/css-library/yarn.lock
  packages/web-components/package.json
  packages/web-components/src/components/va-button-icon/va-button-icon.scss
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
  yarn.lock
Labels: patch

#1241 va-button | use white background on secondary hover
  packages/storybook/stories/styles/va-icon.scss
  packages/web-components/src/components/va-button/va-button.scss
Labels: patch

#1174 va-button: add submit functionality
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
Labels: patch

#1246 Version bumps for next release
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1242 CSS Library: update spacing and font utility classes for 16px root font size
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/fonts.json
  packages/css-library/tokens/spacing.json
Labels: css-library

#1244 fix: v3 breadcrumb padding changes
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
Labels: patch
