Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-11, with the labels that each got.

#1382 css-library: Adding line-length tokens
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/line-lengths.json
Labels: css-library

#1379 CSS Library: add USWDS theme setting for medium-screen breakpoint utilities
  package.json
  packages/css-library/dist/stylesheets/base/fonts.css
  packages/css-library/dist/stylesheets/base/fonts.css.map
  packages/css-library/dist/stylesheets/base/headings.css
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/modules/m-action-link.css
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/uswds-typography.css
  packages/css-library/dist/stylesheets/uswds-typography.css.map
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/package.json
  packages/css-library/src/stylesheets/_uswds-theme.scss
  packages/css-library/src/stylesheets/utilities.scss
  packages/css-library/yarn.lock
  packages/web-components/package.json
  yarn.lock
Labels: css-library

#1388 Update `va-pagination` list item and next and previous links accessible labels for better screen reader consistency
  packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
  packages/web-components/src/components/va-pagination/va-pagination.scss
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#1389 va-telephone: Allow non-US phone numbers
  packages/storybook/stories/va-telephone.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: minor

#1391 Component library release v48.0.0
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1392 update web-components package version for release
  packages/web-components/package.json
Labels: ignore-for-release

#1393 update core and web-component versions for release
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1394 va-on-this-page: updating line-length for list items to use new token
  packages/web-components/src/components/va-on-this-page/va-on-this-page.css
Labels: patch

#1395 DOCS: Update README `Contributing` entry with Verdaccio instructions
  README.md
Labels: ignore-for-release

#1398 Remove alert presentation role
  packages/storybook/.storybook/preview.js
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch

#1399 css-library: add source-sans normalize token, rename base to root
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/stylesheets/utilities.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/tokens/font.scss
  packages/css-library/tokens/fonts.json
Labels: css-library

#1396 va-link: Replacing external icon with text
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.tsx
  packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.tsx
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
Labels: patch

#1397 Update to USWDS v3.9.0
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
  yarn.lock
Labels: patch

#1404 Update version numbers for release and publish
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1386 va-language-toggle: add component
  packages/storybook/stories/va-language-toggle.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
  packages/web-components/src/components/va-language-toggle/va-language-toggle.scss
  packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.tsx
Labels: minor

#1406 va-additional-info & va-alert-expandable: remove slot content from Stencil axe test
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
Labels: patch

#1407 va-link & va-link-action: update analytics tests and lifecycle
  packages/web-components/src/components/va-link-action/test/va-link-action.e2e.ts
  packages/web-components/src/components/va-link-action/va-link-action.tsx
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
Labels: patch

#1410 va-table: update loading lifecycle and fix Stencil axe error
  packages/web-components/src/components/va-table/va-table-inner/va-table-row.tsx
  packages/web-components/src/components/va-table/va-table.tsx
Labels: patch

#1408 va-banner: fix analytics Stencil test warnings
  packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
  packages/web-components/src/components/va-banner/test/va-banner.spec.ts
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: patch

#1413 va-language-toggle: resolve Stencil test warning and errors
  packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
  packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx
Labels: patch

#1415 build: allow vite to lazy load stencil components
  packages/web-components/stencil.config.ts
Labels: minor

#1417 CSS Library: add feedback-related foreground tokens
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/utils.css.map
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/table.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/shame.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
Labels: css-library
