Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-03, with the labels that each got.

#1070 Upgrade USWDS@3.7.1
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-pagination/va-pagination.scss
  yarn.lock
Labels: minor

#1075 va-radio-option: revert z-index and add Formation style overrides for USWDS
  packages/web-components/package.json
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
Labels: patch

#1076 Update core for release v37.2.0
  packages/core/package.json
Labels: ignore-for-release

#1073 Ignore false UI diffs in va-banner and va-loading-indicator
  packages/storybook/stories/va-loading-indicator.stories.jsx
  packages/storybook/stories/va-maintenance-banner.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.css
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
  packages/web-components/src/components/va-maintenance-banner/test/va-maintenance-banner.e2e.ts
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
  yarn.lock
Labels: patch

#1083 va-accordion: remove Font Awesome icon override
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
Labels: patch

#1084 Minimal header optional headings
  packages/storybook/stories/va-header-minimal.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-header-minimal/test/va-header-minimal.spec.tsx
  packages/web-components/src/components/va-header-minimal/va-header-minimal.scss
  packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx
Labels: patch

#1074 CSS-Library: add missing tokens after audit of formation
  packages/css-library/copy-uswds-color-tokens.js
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/figma/colors/variables.json
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
  packages/web-components/src/components/va-accordion/va-accordion.scss
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-back-to-top/va-back-to-top.css
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs-slot.css
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-card/va-card.scss
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.scss
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-header-minimal/va-header-minimal.scss
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.css
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.scss
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-minimal-footer/va-minimal-footer.scss
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-need-help/va-need-help.css
  packages/web-components/src/components/va-notification/va-notification.scss
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss
  packages/web-components/src/components/va-on-this-page/va-on-this-page.css
  packages/web-components/src/components/va-pagination/va-pagination.scss
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-process-list/va-process-list.scss
  packages/web-components/src/components/va-progress-bar/va-progress-bar.css
  packages/web-components/src/components/va-promo-banner/va-promo-banner.css
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-search-input/va-search-input.scss
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.scss
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.scss
  packages/web-components/src/components/va-summary-box/va-summary-box.scss
  packages/web-components/src/components/va-table/va-table-row.css
  packages/web-components/src/components/va-table/va-table.css
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/global/_formation_overrides.scss
  packages/web-components/src/mixins/buttons.css
  packages/web-components/src/mixins/focusable.css
  packages/web-components/src/mixins/form-field-error.css
  packages/web-components/src/mixins/inputs.css
  packages/web-components/src/mixins/links.css
  packages/web-components/src/mixins/uswds-error-border.scss
Labels: minor

#1086 update css-lib version in web-components
  packages/core/package.json
  packages/web-components/package.json
  yarn.lock
Labels: patch

#1087 update tokens missed in previous update
  packages/css-library/dist/elements.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/dist/utilities.css
  packages/css-library/dist/utilities.css.map
  packages/css-library/src/stylesheets/elements.scss
  packages/css-library/src/tokens/color.scss
  packages/css-library/tokens/color.json
  packages/css-library/tokens/uswds.json
Labels: patch

#1089 Bump core to 38.0.2
  packages/core/package.json
Labels: patch

#1091 Add css-library label to release notes
  .github/release.yml
Labels: ignore-for-release

#1088 Update breadcrumb-list guidance
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: ignore-for-release

#1090 2564 - Updating comp-usage script to account for V3 as default
  packages/design-system-dashboard-cli/src/create-spreadsheets.js
Labels: ignore-for-release

#1094 va-checkbox: Add part attribute to label and description
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#1098 Update accordion styling
  packages/storybook/stories/va-accordion-uswds.stories.jsx
  packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
Labels: patch

#1099 Storybook: Move VA specific components in the sidebar
  packages/storybook/stories/va-alert-expandable.stories.jsx
  packages/storybook/stories/va-back-to-top.stories.jsx
  packages/storybook/stories/va-banner.stories.jsx
  packages/storybook/stories/va-card.stories.jsx
  packages/storybook/stories/va-date.stories.jsx
  packages/storybook/stories/va-header-minimal.stories.jsx
  packages/storybook/stories/va-link.stories.jsx
  packages/storybook/stories/va-loading-indicator.stories.jsx
  packages/storybook/stories/va-maintenance-banner.stories.jsx
  packages/storybook/stories/va-minimal-footer.stories.jsx
  packages/storybook/stories/va-need-help.stories.jsx
  packages/storybook/stories/va-official-gov-banner.stories.jsx
  packages/storybook/stories/va-omb-info.stories.jsx
  packages/storybook/stories/va-on-this-page.stories.jsx
  packages/storybook/stories/va-progress-bar.stories.jsx
  packages/storybook/stories/va-promo-banner.stories.jsx
  packages/storybook/stories/va-telephone.stories.jsx
Labels: ignore-for-release

#1103 Storybook: fix sidebar maturity indicators
  packages/storybook/.storybook/manager.js
  packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
Labels: ignore-for-release
