Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-06, with the labels that each got.

#1172 CSS Library: Style adjustments for USWDS typography upgrade
  packages/css-library/dist/base/headings.css
  packages/css-library/dist/base/headings.css.map
  packages/css-library/dist/full.css
  packages/css-library/dist/full.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/dist/uswds-typography.css
  packages/css-library/dist/utilities.css
  packages/css-library/dist/utilities.css.map
  packages/css-library/package.json
  packages/css-library/src/stylesheets/uswds-typography.scss
  packages/css-library/tokens/uswds.json
Labels: css-library

#1177 feat: new link action component
  packages/storybook/stories/action-link.stories.mdx
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-link-action.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link-action/test/va-link-action.e2e.ts
  packages/web-components/src/components/va-link-action/va-link-action.css
  packages/web-components/src/components/va-link-action/va-link-action.tsx
Labels: minor

#1180 va-icon: Adding new icons 6/6/24
  packages/storybook/public/img/sprite.svg
  packages/storybook/stories/va-icon-uswds.stories.jsx
  packages/web-components/src/img/sprite.svg
Labels: patch

#1181 CSS Library: add anchor and button elements to USWDS typeset
  packages/css-library/dist/stylesheets/uswds-typography.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/uswds-typography.scss
  packages/css-library/yarn.lock
Labels: css-library

#1185 m-action-link: remove typeset ui from icon style, update color-green, fix base font-size
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/formation-overrides/_variables.scss
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/modules/m-action-link.css
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/modules/m-alert.css
  packages/css-library/dist/stylesheets/modules/m-form-elements.css
  packages/css-library/dist/stylesheets/modules/m-form-process.css
  packages/css-library/dist/stylesheets/modules/m-nav-sidebar.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/formation-overrides/_variables.scss
  packages/css-library/src/stylesheets/modules/m-action-link.scss
Labels: css-library

#1179 Add USWDS typography to non-USWDS components and Storybook
  .github/workflows/publish-storybook.yml
  package.json
  packages/react-components/package.json
  packages/storybook/.storybook/style.scss
  packages/storybook/package.json
  packages/storybook/stories/Modal.stories.jsx
  packages/storybook/stories/action-link.stories.mdx
  packages/storybook/stories/sidenav.stories.mdx
  packages/storybook/stories/va-additional-info-uswds.stories.jsx
  packages/storybook/stories/va-alert-expandable.stories.jsx
  packages/storybook/stories/va-button-icon.stories.jsx
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/storybook/stories/va-link-action.stories.jsx
  packages/storybook/stories/va-link.stories.jsx
  packages/storybook/stories/va-maintenance-banner.stories.jsx
  packages/storybook/stories/va-telephone.stories.jsx
  packages/storybook/stories/wc-helpers.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-additional-info/va-additional-info.css
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
  packages/web-components/src/components/va-alert/va-alert-slot.css
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-back-to-top/va-back-to-top.css
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.scss
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.tsx
  packages/web-components/src/components/va-date/va-date.css
  packages/web-components/src/components/va-link/va-link.css
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.css
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.scss
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss
  packages/web-components/src/components/va-omb-info/va-omb-info.css
  packages/web-components/src/components/va-on-this-page/va-on-this-page.css
  packages/web-components/src/components/va-promo-banner/va-promo-banner.css
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/components/va-telephone/va-telephone.css
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/mixins/form-field-error.css
  packages/web-components/src/mixins/headers.css
  packages/web-components/src/mixins/hint-text.css
  packages/web-components/src/mixins/inputs.css
  packages/web-components/src/mixins/uswds-error-border.scss
  yarn.lock
Labels: patch

#1187 specify storybook build output dir
  .github/workflows/publish-storybook.yml
Labels: ignore-for-release

#1188 update build command
  .github/workflows/publish-storybook.yml
Labels: ignore-for-release

#1191 va-breadcrumbs: Fix for focusability of 'hidden' breadcrumbs
  packages/web-components/package.json
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss
Labels: patch

#1190 CSS Library: Font normalization QA updates
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/modules/m-megamenu.css
  packages/css-library/dist/stylesheets/modules/m-megamenu.css.map
  packages/css-library/dist/stylesheets/uswds-typography.css
  packages/css-library/dist/stylesheets/uswds-typography.css.map
  packages/css-library/package.json
  packages/css-library/src/stylesheets/formation-overrides/elements/typography.scss
  packages/css-library/src/stylesheets/modules/m-megamenu.scss
  packages/css-library/src/stylesheets/uswds-typography.scss
  packages/css-library/yarn.lock
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
Labels: css-library

#1183 va-link: new icon variant
  packages/storybook/stories/va-link.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.css
  packages/web-components/src/components/va-link/va-link.tsx
Labels: minor

#1192 va-file-input: show modal to confirm file delete
  packages/web-components/package.json
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1184 2643 - va-file-input-multiple
  packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/FileIndex.ts
  packages/web-components/src/components/va-file-input-multiple/test/1x1.png
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.scss
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1196 update core version for release
  packages/core/package.json
Labels: ignore-for-release

#1197 update publish script
  .github/workflows/publish.yml
Labels: ignore-for-release

#1199 patch update
  packages/core/package.json
Labels: ignore-for-release

#1200 update web component to 10.0.1
  packages/web-components/package.json
Labels: ignore-for-release

#1195 Updating usage script to start counting instances of Font Awesome icons
  packages/design-system-dashboard-cli/src/create-spreadsheets.js
Labels: ignore-for-release

#1202 va-alert: add specificity to slot style
  packages/web-components/package.json
  packages/web-components/src/components/va-alert/va-alert-slot.css
Labels: patch

#1203 Update core version for release v42.2.2
  packages/core/package.json
Labels: ignore-for-release

#1198 CSS Library: add linked header style
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/modules/m-megamenu.css
  packages/css-library/dist/stylesheets/modules/m-megamenu.css.map
  packages/css-library/package.json
  packages/css-library/src/stylesheets/formation-overrides/elements/typography.scss
  packages/css-library/src/stylesheets/modules/m-megamenu.scss
  packages/css-library/src/stylesheets/site/_m-vet-nav.scss
Labels: css-library

#1205 css-library: Update to _core-variables.scss to change $image-path to /img
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/modules/m-dropdown.css
  packages/css-library/dist/stylesheets/modules/m-external-link.css
  packages/css-library/dist/stylesheets/modules/m-hub-page-link-list.css
  packages/css-library/dist/stylesheets/modules/m-nav-sidebar.css
  packages/css-library/dist/stylesheets/shame.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/_core-variables.scss
Labels: css-library

#1207 Dashboard-CLI: Modifying how we tabulate icons
  packages/design-system-dashboard-cli/src/create-spreadsheets.js
  packages/design-system-dashboard-cli/src/write-comp-usage-to-csv.js
Labels: ignore-for-release

#1208 va-memorable-date: add props to support custom error messages for day, month, or year
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: minor

#1210 Add export to Breadcrumb type so components.d.ts can find it
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: patch

#1212 Rename Additional Info in file input to Additional Form Inputs
  packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
  packages/storybook/stories/va-file-input-uswds.stories.jsx
Labels: ignore-for-release

#1215 add anchor tag to va-textintro
  packages/css-library/package.json
  packages/css-library/src/stylesheets/base/va.scss
Labels: css-library
