Repository department-of-veterans-affairs/component-library, pull requests merged in 2024-02, with the labels that each got.

#1046 va-file-input - Disabling multiple file inputs temporarily
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input-upgrader.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: major

#1047 ExpandingGroup: Remove deprecated React component
  packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/react-components/index.js
  packages/react-components/package.json
  packages/react-components/src/components/ExpandingGroup/ExpandingGroup.jsx
  packages/react-components/src/components/ExpandingGroup/ExpandingGroup.mdx
  packages/react-components/src/components/ExpandingGroup/ExpandingGroup.unit.spec.jsx
  packages/react-components/src/index.js
  packages/storybook/stories/ExpandingGroup.stories.jsx
Labels: major

#1049 va-text-input: require prop to enable character count
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/va-text-input.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/utils/utils.ts
Labels: minor

#1051 bump core for release
  packages/core/package.json
Labels: minor

#1050 va-file-input: stop multiple file drag and drop
  packages/web-components/src/components/va-file-input/va-file-input-upgrader.ts
Labels: patch

#1052 dashboard-cli - Add CSV output of different version counts
  .gitignore
  packages/design-system-dashboard-cli/jest.config.js
  packages/design-system-dashboard-cli/package.json
  packages/design-system-dashboard-cli/src/codeowners.json
  packages/design-system-dashboard-cli/src/create-spreadsheets.js
  packages/design-system-dashboard-cli/src/find-ds-components.js
  packages/design-system-dashboard-cli/src/write-comp-usage-to-csv.js
  packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
  packages/design-system-dashboard-cli/test/write-react-owners-to-csv.spec.js
  update-component-usage.sh
Labels: ignore-for-release

#1054 Rename va-featured-content to va-summary-box
  packages/storybook/stories/va-summary-box-uswds.stories.jsx
  packages/storybook/stories/va-summary-box.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-summary-box/test/va-summary-box.e2e.ts
  packages/web-components/src/components/va-summary-box/va-summary-box.scss
  packages/web-components/src/components/va-summary-box/va-summary-box.tsx
Labels: major

#1055 Bump core version for release
  packages/core/package.json
Labels: major

#1053 Fix va-radio uswds v3 overlap
  packages/storybook/stories/va-radio.stories.jsx
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
Labels: bug, patch

#1056 va-radio: Show label and required for all forms pattern options
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-radio/va-radio.tsx
Labels: patch

#1057 va-modal: fix icon positioning bug
  packages/web-components/package.json
  packages/web-components/src/components/va-modal/va-modal.scss
Labels: patch

#1060 va-pagination: remove active button background color, override overflow opacity
  packages/web-components/package.json
  packages/web-components/src/components/va-pagination/va-pagination.scss
Labels: patch

#1059 va-file-input: Add focus border, fix input alignment, and update error state
  packages/web-components/package.json
  packages/web-components/src/components/va-file-input/va-file-input.scss
Labels: patch

#1062 va-maintenance-banner: Removing maintenance banner's banner role
  packages/web-components/src/components/va-maintenance-banner/test/va-maintenance-banner.e2e.ts
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
Labels: patch

#1061 va-file-input: Fix for screen readers not reading changed file name
  packages/web-components/src/components/va-file-input/va-file-input-upgrader.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1064 Forms Pattern - update to make headings serif font
  packages/css-library/dist/elements.css
  packages/css-library/dist/elements.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/elements.scss
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
  packages/web-components/src/components/va-number-input/va-number-input.scss
  packages/web-components/src/components/va-radio/va-radio.scss
  packages/web-components/src/components/va-text-input/va-text-input.scss
  packages/web-components/src/components/va-textarea/va-textarea.scss
  yarn.lock
Labels: minor

#1069 Updating Chromatic Link in Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#1066 va-breadcrumbs: first breadcrumb label defaults to "VA.gov home"
  packages/storybook/stories/va-breadcrumbs-uswds.stories.jsx
  packages/storybook/stories/va-breadcrumbs.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: minor

#1067 2353 Updates image resource path for va-icon & va-pagination
  packages/core/package.json
  packages/core/webpack.config.js
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-icon/va-icon.tsx
  packages/web-components/src/components/va-pagination/va-pagination.tsx
Labels: patch

#1072 Version bump to 37.1.0
  packages/core/package.json
Labels: ignore-for-release
