Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-04, with the labels that each got.

#1556 CSS-Library: remove custom list styles
  .github/workflows/chromatic.yml
  .github/workflows/node.js.yml
  .github/workflows/publish-storybook.yml
  .github/workflows/publish.yml
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/modules/m-process-list.css
  packages/css-library/dist/stylesheets/modules/m-process-list.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/base/va.scss
  packages/css-library/src/stylesheets/modules/m-process-list.scss
  packages/web-components/src/components/va-link/va-link.tsx
Labels: css-library

#1545 va-button: increase line-height
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/fonts.json
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
Labels: patch

#1559 CSS-library: add semantic gutter tokens
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/spacing.json
Labels: css-library

#1553 va-critical-action: focus state styling updates and rename component
  packages/storybook/stories/va-critical-action.stories.jsx
  packages/storybook/stories/va-service-list-item.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-critical-action/test/va-critical-action.e2e.ts
  packages/web-components/src/components/va-critical-action/va-critical-action.scss
  packages/web-components/src/components/va-critical-action/va-critical-action.tsx
  packages/web-components/src/components/va-service-list-item/test/va-service-list-item.e2e.ts
  packages/web-components/src/components/va-service-list-item/va-service-list-item.tsx
Labels: minor

#1560 va-alert: add action link Storybook example & adjust header alignment
  packages/storybook/stories/va-alert-uswds.stories.tsx
  packages/web-components/src/components/va-alert/va-alert-slot.css
  packages/web-components/src/components/va-banner/va-banner.css
Labels: patch

#1562 va-file-input: Updates hint text within stories
  packages/storybook/stories/va-file-input-uswds.stories.tsx
Labels: ignore-for-release

#1557 va-alert, va-maintenance-banner, va-modal, va-promo-banner: close icon
  packages/web-components/src/components/va-alert/va-alert.scss
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.scss
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-promo-banner/va-promo-banner.css
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: patch

#1563 va-critical-action: staging review updates
  packages/storybook/stories/va-critical-action.stories.jsx
  packages/storybook/stories/va-service-list-item.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-critical-action/va-critical-action.scss
  packages/web-components/src/components/va-critical-action/va-critical-action.tsx
  packages/web-components/src/components/va-service-list-item/test/va-service-list-item.e2e.ts
  packages/web-components/src/components/va-service-list-item/va-service-list-item.tsx
Labels: patch

#1550 va-combo-box: aria status to include opt group count
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
Labels: patch

#1565 va-breadcrumb: add prop to conditionally use #content or a custom href for the current page
  packages/storybook/stories/va-breadcrumbs-uswds.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
  packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
Labels: minor

#1555 va-memorable-date: change lifecycle method for handling dash
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: patch

#1566 CSS-Library: add block display to eyebrow styling class
  packages/css-library/dist/stylesheets/modules/m-eyebrow.css
  packages/css-library/dist/stylesheets/modules/m-eyebrow.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/modules/m-eyebrow.scss
  packages/storybook/stories/Eyebrow.stories.mdx
  packages/storybook/stories/Eyebrow.stories.tsx
Labels: css-library

#1567 Update package versions for release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1554 Storybook Form Patterns: add bottom margin to slot list content
  packages/storybook/stories/va-checkbox-group-uswds.stories.tsx
  packages/storybook/stories/va-memorable-date-uswds.stories.tsx
  packages/storybook/stories/va-radio-uswds.stories.tsx
  packages/storybook/stories/va-select-uswds.stories.tsx
  packages/storybook/stories/va-text-input-uswds.stories.tsx
  packages/storybook/stories/va-textarea-uswds.stories.tsx
Labels: ignore-for-release

#1569 va-service-list-item: support all va-link props via shared interface
  packages/storybook/stories/va-service-list-item.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link/va-link.tsx
  packages/web-components/src/components/va-service-list-item/test/va-service-list-item.e2e.ts
  packages/web-components/src/components/va-service-list-item/va-service-list-item.tsx
Labels: patch

#1573 Expand story when modal is open
  packages/storybook/.storybook/style.scss
  packages/storybook/stories/va-modal-uswds.stories.tsx
  packages/storybook/stories/wc-helpers.tsx
Labels: ignore-for-release

#1571 css-library: remove legacy accordion styles
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/core.scss
  packages/css-library/src/stylesheets/formation-overrides/components/_accordions.scss
Labels: minor

#1570 va-link-action: add primary-entry variation [Amends #4001]
  .nvmrc
  package.json
  packages/storybook/stories/va-link-action.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-link-action/test/va-link-action.e2e.ts
  packages/web-components/src/components/va-link-action/va-link-action.css
  packages/web-components/src/components/va-link-action/va-link-action.scss
  packages/web-components/src/components/va-link-action/va-link-action.tsx
  setup.sh
Labels: minor

#1575 Bump repo semver for 50.2.0
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1576 va-critical-action: update padding
  packages/web-components/src/components/va-critical-action/va-critical-action.scss
Labels: patch

#1574 va-alert-expandable: align content with title
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/utils.css.map
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/core/base.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/labels.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/modules/m-additional-info.css.map
  packages/css-library/dist/stylesheets/modules/m-alert.css.map
  packages/css-library/dist/stylesheets/modules/m-breadcrumbs.css.map
  packages/css-library/dist/stylesheets/modules/m-dropdown.css.map
  packages/css-library/dist/stylesheets/modules/m-emergency-banner.css.map
  packages/css-library/dist/stylesheets/modules/m-eyebrow.css.map
  packages/css-library/dist/stylesheets/modules/m-form-process.css.map
  packages/css-library/dist/stylesheets/modules/m-homepage-hero.css.map
  packages/css-library/dist/stylesheets/modules/m-hub-page-link-list.css.map
  packages/css-library/dist/stylesheets/modules/m-maintenance-banner.css.map
  packages/css-library/dist/stylesheets/modules/m-megamenu.css.map
  packages/css-library/dist/stylesheets/modules/m-modal.css.map
  packages/css-library/dist/stylesheets/modules/m-nav-sidebar.css.map
  packages/css-library/dist/stylesheets/modules/m-process-list.css.map
  packages/css-library/dist/stylesheets/modules/va-pagination.css.map
  packages/css-library/dist/stylesheets/modules/va-tabs.css.map
  packages/css-library/dist/stylesheets/shame.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/tokens/color.json
  packages/web-components/package.json
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
  yarn.lock
Labels: patch

#1579 va-combo-box: prevent clear input button from being hidden
  packages/web-components/src/components/va-combo-box/va-combo-box.scss
Labels: patch

#1581 va-file-input and va-file-input-multiple: Add link to platform documentation for encrypted PDFs
  packages/storybook/stories/va-file-input-multiple-uswds.stories.tsx
  packages/storybook/stories/va-file-input-uswds.stories.tsx
Labels: ignore-for-release

#1577 va-loading-indicator: fix TypeError
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
Labels: patch

#1582 va-alert: fix TypeError for close button aria label
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch

#1583 update package versions for release v50.2.1
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1584 va-service-list-item: update focus & active state style
  packages/web-components/src/components/va-service-list-item/va-service-list-item.scss
Labels: patch

#1585 va-icon: Add mobile icons
  packages/storybook/public/img/sprite.svg
  packages/storybook/stories/va-icon-uswds.stories.tsx
  packages/web-components/src/img/sprite.svg
Labels: patch
