Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-01, with the labels that each got.

#1441 CSS Library: add `img` folder to dist
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  yarn.lock
Labels: css-library

#1444 css-library: Fixing the html element's font-size so it will respect browser settings
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/src/stylesheets/base/va.scss
  packages/css-library/src/stylesheets/formation-overrides/elements/typography.scss
Labels: css-library

#1445 va-accordion: add custom event to expand/collapse all button
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#1446 va-button: add loading variation
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
Labels: minor

#1449 va-alert-expandable & va-alert-sign-in: fix Storybook link to guidance
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx
Labels: ignore-for-release

#1447 va-date: remove unnecessary aria labels for select
  packages/web-components/src/components/va-date/va-date.tsx
Labels: patch

#1452 va-alert-sign-in: Hides no-sign-in-link when not present
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx
Labels: patch

#1451 Add mock buttons
  packages/storybook/stories/va-alert-sign-in.stories.jsx
Labels: ignore-for-release

#1448 va-link: add aria-label to all variations
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.tsx
Labels: patch

#1453 update versions for release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1455 va-telephone: add health resource center number to constants
  packages/react-components/src/components/Telephone/contacts.js
  packages/web-components/src/contacts.ts
Labels: patch

#1458 va-file-input-multiple: allow for slots to be conditionally rendered on file inputs
  packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
Labels: minor

#1454 Create FORMATION_MIGRATION.md
  packages/css-library/FORMATION_MIGRATION.md
Labels: ignore-for-release

#1456 Updated prefill pattern components in Storybook
  packages/storybook/stories/pattern-prefill/va-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-alert-with-editable-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-alert.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-signed-in.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefilled-info-with-editable-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefilled-info-with-uneditable-card.stories.jsx
Labels: ignore-for-release

#1464 va-alert-sign-in: update story time-limit to 60 days
  packages/storybook/stories/va-alert-sign-in.stories.jsx
Labels: ignore-for-release

#1466 va-select: Adding 'vaSelectBlur' event
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
Labels: patch

#1460 va-file-input-multiple: update data for vaMultipleChange to return more detail (BREAKING) va-file-input: fix bug with upload message not resetting
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: major

#1442 va-checkbox and va-radio-option: Improved a11y
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/color.json
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.tsx
  packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
Labels: patch

#1467 va-alert: Fixing it so close button on slim alerts doesn't overflow
  packages/web-components/src/components/va-alert/va-alert.scss
Labels: patch

#1468 CSS-Library: add primitive and semantic spacing tokens
  packages/css-library/config.js
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/base/va.scss
  packages/css-library/tokens/color.json
  packages/css-library/tokens/spacing.json
  packages/css-library/tokens/uswds-spacing.json
Labels: css-library

#1463 va-file-input: add statusText prop
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1472 Update versions for release
  README.md
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release
