Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-09, with the labels that each got.

#1753 Weekly Design System Reports - 2025-09-03
  packages/design-system-dashboard-cli/output/ds-components-2025-09-03.csv
  packages/design-system-dashboard-cli/output/form-apps-2025-09-03.csv
  packages/design-system-dashboard-cli/output/forms-library-usage-2025-09-03.txt
Labels: ignore-for-release

#1751 Storybook: add customYearErrorMessage to va-memorable-date date of birth stories
  packages/storybook/stories/va-memorable-date-uswds.stories.tsx
Labels: ignore-for-release

#1762 va-button-segmented: Update styles for two/three buttons
  packages/storybook/stories/va-button-segmented.stories.tsx
  packages/web-components/src/components/va-button-segmented/test/va-button-segmented.e2e.ts
  packages/web-components/src/components/va-button-segmented/va-button-segmented.scss
  packages/web-components/src/components/va-button-segmented/va-button-segmented.tsx
Labels: patch

#1766 Fix spelling of Sojourner in Storybook
  packages/storybook/stories/va-checkbox-group-uswds.stories.tsx
Labels: ignore-for-release

#1768 va-textarea: Fix horizontal overflow at high zoom
  packages/web-components/src/components/va-textarea/va-textarea.scss
Labels: patch

#1772 va-accordion: Create separate buttons for "expand all" and "collapse all"
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.scss
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: minor

#1752 VaTable: Interactive elements
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table.tsx
Labels: patch

#1779 va-button-segmented: Update details payload for analytics event
  packages/web-components/src/components/va-button-segmented/va-button-segmented.tsx
Labels: patch

#1787 va-text-input: Add password type variation / va-file-input: Use new password variation to mask file password.
  packages/storybook/stories/va-file-input-multiple-uswds.stories.tsx
  packages/storybook/stories/va-file-input-uswds.stories.tsx
  packages/storybook/stories/va-text-input-uswds.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1791 Storybook: Disable unused chromatic snapshots
  packages/storybook/stories/Modal.stories.tsx
  packages/storybook/stories/action-link.stories.js
  packages/storybook/stories/pattern-prefill/va-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-alert.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-signed-in.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefilled-info-with-editable-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefilled-info-with-uneditable-card.stories.jsx
  packages/storybook/stories/va-accordion-uswds.stories.tsx
  packages/storybook/stories/va-additional-info-uswds.stories.tsx
  packages/storybook/stories/va-alert-uswds.stories.tsx
  packages/storybook/stories/va-back-to-top.stories.tsx
  packages/storybook/stories/va-banner.stories.tsx
  packages/storybook/stories/va-breadcrumbs-uswds.stories.tsx
  packages/storybook/stories/va-button-icon.stories.tsx
  packages/storybook/stories/va-button-uswds.stories.tsx
  packages/storybook/stories/va-checkbox-group-uswds.stories.tsx
  packages/storybook/stories/va-checkbox-uswds.stories.tsx
  packages/storybook/stories/va-combo-box-uswds.stories.tsx
  packages/storybook/stories/va-date.stories.tsx
  packages/storybook/stories/va-file-input-multiple-uswds.stories.tsx
  packages/storybook/stories/va-file-input-uswds.stories.tsx
  packages/storybook/stories/va-icon-uswds.stories.tsx
  packages/storybook/stories/va-link.stories.tsx
  packages/storybook/stories/va-loading-indicator.stories.tsx
  packages/storybook/stories/va-modal-uswds.stories.tsx
  packages/storybook/stories/va-notification.stories.tsx
  packages/storybook/stories/va-omb-info.stories.tsx
  packages/storybook/stories/va-on-this-page.stories.tsx
  packages/storybook/stories/va-pagination-uswds.stories.tsx
  packages/storybook/stories/va-privacy-agreement-uswds.stories.tsx
  packages/storybook/stories/va-promo-banner.stories.tsx
  packages/storybook/stories/va-radio-uswds.stories.tsx
  packages/storybook/stories/va-search-input-uswds.stories.tsx
  packages/storybook/stories/va-segmented-progress-bar-uswds.stories.tsx
  packages/storybook/stories/va-select-uswds.stories.tsx
  packages/storybook/stories/va-sidenav.stories.tsx
  packages/storybook/stories/va-tabs.stories.tsx
  packages/storybook/stories/va-telephone.stories.tsx
  packages/storybook/stories/va-text-input-uswds.stories.tsx
  packages/storybook/stories/va-textarea-uswds.stories.tsx
Labels: ignore-for-release

#1790 Weekly Design System Reports - 2025-09-18
  packages/design-system-dashboard-cli/output/ds-components-2025-09-18.csv
  packages/design-system-dashboard-cli/output/form-apps-2025-09-18.csv
  packages/design-system-dashboard-cli/output/forms-library-usage-2025-09-18.txt
Labels: ignore-for-release

#1796 Weekly Design System Reports - 2025-09-25
  packages/design-system-dashboard-cli/output/ds-components-2025-09-25.csv
  packages/design-system-dashboard-cli/output/form-apps-2025-09-25.csv
  packages/design-system-dashboard-cli/output/forms-library-usage-2025-09-25.txt
Labels: ignore-for-release

#1798 va-text-input: add the vaInput custom event
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor
