Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-08, with the labels that each got.

#1707 va-omb-info: Add accessible description to OMB button
  packages/storybook/stories/va-omb-info.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-omb-info/va-omb-info.tsx
Labels: patch

#1719 va-sidenav: enhance current-page handling for truthy and false values
  packages/web-components/src/components/va-sidenav/test/va-sidenav-item.e2e.ts
  packages/web-components/src/components/va-sidenav/test/va-sidenav.e2e.ts
  packages/web-components/src/components/va-sidenav/va-sidenav.tsx
Labels: patch

#1721 Display the correct React binding name for va-telephone-input in Storybook
  packages/storybook/stories/va-telephone-input.stories.tsx
Labels: ignore-for-release

#1722 va-sidenav: use medium-screen breakpoint for mobile view
  packages/web-components/src/components/va-sidenav/va-sidenav.tsx
Labels: patch

#1718 va-alert: add the slim prop if no headline is provided
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
  packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: patch

#1691 va-modal and va-omb-info: Restore focus to trigger element after modal close
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-omb-info/test/va-omb-info.e2e.ts
Labels: patch

#1723 <va-accordion-item>: update styles for header and subheader to prevent icon alignment issues on Chrome
  packages/web-components/src/components/va-accordion/va-accordion-item.scss
  packages/web-components/src/components/va-accordion/va-accordion-item.tsx
Labels: patch

#1725 CSS-Library: update heading to correct values and use rem
  packages/css-library/dist/stylesheets/base/headings.css
  packages/css-library/dist/stylesheets/base/utils.css
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/formation-overrides/_variables.scss
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/labels.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/shame.css
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/package.json
  packages/css-library/src/stylesheets/base/headings.scss
  packages/css-library/src/stylesheets/formation-overrides/_variables.scss
  packages/css-library/tokens/fonts.json
Labels: css-library

#1733 va-link: Fix icon line breaking issue for "active" variant
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.scss
  packages/web-components/src/components/va-link/va-link.tsx
Labels: patch

#1727 va-file-input: update “remove” to “delete”
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1735 va-segmented-progress-bar: Improve clarity of screen reader announcement
  packages/storybook/stories/va-segmented-progress-bar-uswds.stories.tsx
  packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
  packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
Labels: patch

#1717 va-file-input-multiple: changes for forms system integration
  packages/storybook/stories/va-file-input-uswds.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/test/placeholder.png
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1743 bump versions for 52.1.0 release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1744 va-telephone-input: Correct width/media query breakpoint
  packages/web-components/src/components/va-telephone-input/va-telephone-input.scss
Labels: patch
