Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-06, with the labels that each got.

#1619 Re-add subnav content that was lost in migration
  packages/storybook/.storybook/main.ts
  packages/storybook/package.json
  packages/storybook/stories/sidenav.stories.js
  yarn.lock
Labels: ignore-for-release

#1624 va-input-telephone: Update maturity value
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx
Labels: patch

#1614 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: ignore-for-release

#1625 va-link | Fix external link text wrapping
  packages/storybook/stories/va-link.stories.tsx
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.tsx
Labels: patch

#1627 va-input-telephone: improve grammar of error message
  packages/web-components/src/components/va-input-telephone/test/va-input-telephone.e2e.ts
  packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: minor

#1631 va-input-telephone: Delay phone number validation until blur
  packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx
Labels: patch

#1630 va-combo-box: Restore filtering functionality
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
Labels: patch

#1626 va-input-telephone: Improve screen reader experience and fix re-selection display error
  packages/web-components/src/components/va-combo-box/test/utils.spec.tsx
  packages/web-components/src/components/va-combo-box/utils.tsx
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
  packages/web-components/src/components/va-combo-box/va-combo-box.scss
  packages/web-components/src/components/va-input-telephone/va-input-telephone.scss
  packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx
Labels: patch

#1629 `va-textarea`: Fix hint to ensure font-weight is normal
  packages/storybook/stories/va-textarea-uswds.stories.tsx
  packages/web-components/src/components/va-textarea/va-textarea.scss
Labels: patch

#1648 `<va-checkbox-group>` & `<va-radio>` - Fix font-weight of hint when both hint and error are set
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
  packages/web-components/src/components/va-radio/va-radio.scss
Labels: patch

#1647 va-button-segmented - add new component
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/color.json
  packages/storybook/stories/va-button-segmented.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-segmented/test/va-button-segmented.e2e.ts
  packages/web-components/src/components/va-button-segmented/va-button-segmented.scss
  packages/web-components/src/components/va-button-segmented/va-button-segmented.tsx
  packages/web-components/src/components/va-button-segmented/va-button-segmented.types.tsx
Labels: patch, css-library

#1661 va-telephone-input: rename component and add prop to toggle internal errors
  packages/storybook/stories/va-telephone-input.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone-input/test/utils.spec.tsx
  packages/web-components/src/components/va-telephone-input/test/va-input-telephone.e2e.ts
  packages/web-components/src/components/va-telephone-input/utils.tsx
  packages/web-components/src/components/va-telephone-input/va-telephone-input.scss
  packages/web-components/src/components/va-telephone-input/va-telephone-input.tsx
Labels: major

#1662 bump version to 51.0.0
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1654 va-statement-of-truth: add prop to hide legal note
  packages/storybook/stories/va-statement-of-truth-uswds.stories.tsx
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
Labels: minor

#1653 va-promo-banner: update maturity level to deprecated
  packages/storybook/stories/va-promo-banner.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx
Labels: minor

#1660 va-icon: allow for custom sprite path
  packages/storybook/stories/va-icon-uswds.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/img/test.svg
  packages/web-components/src/components/va-icon/test/va-icon.e2e.ts
  packages/web-components/src/components/va-icon/test/va-icon.unit.spec.ts
  packages/web-components/src/components/va-icon/va-icon-global.ts
  packages/web-components/src/components/va-icon/va-icon.tsx
  packages/web-components/src/index.ts
Labels: minor

#1665 Bump ver to 51.1.0
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release
