Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-03, with the labels that each got.

#1509 Prevent nested va-accordion-items from propagating up
  packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#1511 Updating component maturity levels Q1 2025
  packages/storybook/stories/additional-docs.js
  packages/storybook/stories/va-file-input.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
  packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
  packages/web-components/src/components/va-button-icon/va-button-icon.tsx
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-card/va-card.tsx
  packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.tsx
  packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx
  packages/web-components/src/components/va-icon/va-icon.tsx
  packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx
  packages/web-components/src/components/va-link-action/va-link-action.tsx
  packages/web-components/src/components/va-link/va-link.tsx
  packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx
  packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
  packages/web-components/src/components/va-minimal-footer/va-minimal-footer.tsx
  packages/web-components/src/components/va-modal/va-modal.tsx
  packages/web-components/src/components/va-need-help/va-need-help.tsx
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
  packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.tsx
  packages/web-components/src/components/va-process-list/va-process-list.tsx
  packages/web-components/src/components/va-progress-bar/va-progress-bar.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-search-input/va-search-input.tsx
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
  packages/web-components/src/components/va-table/va-table.tsx
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: ignore-for-release

#1510 va-select: add forms patterns support
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/utils/utils.ts
Labels: minor

#1512 va-button: Adding a fullWidth prop
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.scss
  packages/web-components/src/components/va-button/va-button.tsx
Labels: minor

#1500 va-file-input: add percent upload support
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.scss
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1516 va-file-input: Add back default args for storybook example
  packages/storybook/stories/va-file-input-uswds.stories.jsx
Labels: ignore-for-release

#1513 va-checkbox: add normalized font size token to label
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
Labels: patch

#1514 Checkbox aria checked
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#1518 Storybook: Capitalize first letter in focus button labels
  packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
  packages/storybook/stories/va-memorable-date-uswds.stories.jsx
  packages/storybook/stories/va-radio-uswds.stories.jsx
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/storybook/stories/va-text-input-uswds.stories.jsx
  packages/storybook/stories/va-textarea-uswds.stories.jsx
Labels: ignore-for-release

#1520 va-need-help: align header font-size with Figma
  packages/web-components/src/components/va-need-help/va-need-help.css
Labels: patch

#1515 va-checkbox | Fix interactive elements in description
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: patch

#1521 Storybook: update background color for the use with caution label
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#1517 va-select: Adding a full-width prop
  packages/storybook/stories/va-select-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-select/test/va-select.e2e.ts
  packages/web-components/src/components/va-select/va-select.scss
  packages/web-components/src/components/va-select/va-select.tsx
Labels: minor

#1527 Version bump for release 3-12-2025
  packages/core/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1522 va-service-list-item: adjust styling from design feedback
  packages/storybook/stories/va-service-list-item.stories.jsx
  packages/web-components/src/components/va-service-list-item/va-service-list-item.scss
  packages/web-components/src/components/va-service-list-item/va-service-list-item.tsx
Labels: patch

#1529 Revert "va-checkbox | Fix interactive elements in description"
  packages/core/package.json
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/package.json
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: patch

#1528 Storybook: replace deprecated action link class with web component
  packages/storybook/stories/wc-helpers.jsx
Labels: ignore-for-release

#1523 va-checkbox: swap out legend element
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: minor

#1530 Adds setup script and yarn task.
  .yarnrc.yml
  package.json
  setup.sh
Labels: ignore-for-release

#1534 va-official-gov-banner: swap icons
  packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
Labels: patch

#1535 Use headline text for alert close button ARIA label
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
  packages/web-components/src/components/va-alert/va-alert.tsx
Labels: patch

#1531 va-checkbox | Fix interactive elements in description
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: patch

#1537 va-combo-box: user typed matches auto-select
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
  packages/web-components/src/components/va-combo-box/va-combo-box.scss
Labels: patch

#1538 Form Components: add message-aria-describedby checks
  packages/storybook/stories/va-telephone.stories.tsx
  packages/web-components/src/components/va-button/va-button.tsx
  packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
  packages/web-components/src/components/va-combo-box/va-combo-box.tsx
  packages/web-components/src/components/va-link-action/va-link-action.tsx
  packages/web-components/src/components/va-radio/va-radio.tsx
  packages/web-components/src/components/va-select/va-select.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: patch

#1541 Storybook: default va-process-list-item now "controllable"
  packages/storybook/stories/va-process-list-uswds.stories.tsx
Labels: ignore-for-release

#1508 CSS-Library: align list styles to uswds
  packages/css-library/dist/stylesheets/base/va.css
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/elements/lists.css
  packages/css-library/dist/stylesheets/elements/lists.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/lists.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/lists.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/base/va.scss
  packages/css-library/src/stylesheets/core.scss
  packages/css-library/src/stylesheets/elements/lists.scss
  packages/css-library/src/stylesheets/formation-overrides/elements/lists.scss
Labels: css-library

#1547 update package versions
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1546 va-language-toggle: Adds two language variation story
  packages/storybook/stories/va-language-toggle.stories.tsx
Labels: ignore-for-release

#1540 va-date: remove empty options
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
Labels: patch

#1536 va-memorable-date: Replace date processing
  packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
  packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
Labels: bug, patch

#1544 va-combo-box: handle deleting the selected value with keyboard
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
Labels: patch

#1552 va-link | Remove duplicate screen reader content
  packages/web-components/src/components/va-link/test/va-link.e2e.ts
  packages/web-components/src/components/va-link/va-link.scss
  packages/web-components/src/components/va-link/va-link.tsx
Labels: patch

#1551 va-date | Show default days with no month selected
  packages/web-components/src/components/va-date/test/va-date.e2e.ts
  packages/web-components/src/components/va-date/va-date.tsx
  packages/web-components/src/utils/date-utils.ts
Labels: patch

#1549 va-telephone vanity to allow full replacement
  packages/storybook/stories/va-telephone.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: patch
