Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-07, with the labels that each got.

#1669 va-file-input: Updates modal text
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1592 Add examples for integrating VA Design System into projects outside of vets-website
  README.md
  packages/integration-examples/README.md
  packages/integration-examples/vite-react-typescript/.gitignore
  packages/integration-examples/vite-react-typescript/README.md
  packages/integration-examples/vite-react-typescript/index.html
  packages/integration-examples/vite-react-typescript/package-lock.json
  packages/integration-examples/vite-react-typescript/package.json
  packages/integration-examples/vite-react-typescript/public/img/sprite.svg
  packages/integration-examples/vite-react-typescript/src/App.css
  packages/integration-examples/vite-react-typescript/src/App.tsx
  packages/integration-examples/vite-react-typescript/src/fonts/font-face.scss
  packages/integration-examples/vite-react-typescript/src/index.scss
  packages/integration-examples/vite-react-typescript/src/index.tsx
  packages/integration-examples/vite-react-typescript/src/lib/types/va-components.d.ts
  packages/integration-examples/vite-react-typescript/src/lib/va-component-library-setup.ts
  packages/integration-examples/vite-react-typescript/tsconfig.json
  packages/integration-examples/vite-react-typescript/tsconfig.node.json
  packages/integration-examples/vite-react-typescript/vite.config.ts
  packages/integration-examples/vite-react-typescript/yarn.lock
  packages/storybook/stories/va-telephone-input.stories.tsx
Labels: ignore-for-release

#1642 Dependency update: Upgrade to Storybook 9
  packages/react-components/package.json
  packages/react-components/testing/karma.conf.js
  packages/storybook/.storybook/main.ts
  packages/storybook/.storybook/manager.js
  packages/storybook/.storybook/preview.js
  packages/storybook/package.json
  packages/storybook/stories/action-link.mdx
  packages/storybook/stories/how-to-use-storybook.mdx
  packages/storybook/stories/introduction.mdx
  packages/storybook/stories/sidenav.mdx
  packages/storybook/stories/tag.mdx
  packages/storybook/stories/va-accordion-uswds.stories.tsx
  packages/storybook/stories/va-link-action.stories.tsx
  yarn.lock
Labels: ignore-for-release

#1675 va-table: prevent table slot attributes from being added to nested spans
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table.tsx
Labels: patch

#1667 va-button-icon - Update spacing between icon and label text
  packages/web-components/src/components/va-button-icon/va-button-icon.scss
Labels: patch

#1676 va-button, va-button-icon: fix for focus outline getting covered up
  packages/web-components/src/components/va-button-icon/va-button-icon.scss
  packages/web-components/src/components/va-button/va-button.scss
Labels: patch

#1678 va-button-segmented - Temporary fix for button flicker
  packages/web-components/src/components/va-button-segmented/va-button-segmented.scss
  packages/web-components/src/components/va-button-segmented/va-button-segmented.tsx
  packages/web-components/src/mixins/focusable-no-offset.css
Labels: patch

#1690 Add a link to consumer install instructions in the component-library README
  README.md
Labels: ignore-for-release

#1658 va-sidenav: add component
  packages/storybook/.storybook/modes.js
  packages/storybook/stories/va-breadcrumbs-uswds.stories.tsx
  packages/storybook/stories/va-sidenav.stories.tsx
  packages/storybook/types.d.ts
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-sidenav/test/va-sidenav-item.e2e.ts
  packages/web-components/src/components/va-sidenav/test/va-sidenav-submenu.e2e.ts
  packages/web-components/src/components/va-sidenav/test/va-sidenav.e2e.ts
  packages/web-components/src/components/va-sidenav/va-sidenav-item.scss
  packages/web-components/src/components/va-sidenav/va-sidenav-item.tsx
  packages/web-components/src/components/va-sidenav/va-sidenav-submenu.scss
  packages/web-components/src/components/va-sidenav/va-sidenav-submenu.tsx
  packages/web-components/src/components/va-sidenav/va-sidenav.scss
  packages/web-components/src/components/va-sidenav/va-sidenav.tsx
  packages/web-components/src/mixins/focusable.css
Labels: minor

#1688 va-file-input: add more docs to encrypted prop
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1621 Chromatic Deployment: remove skip for dependabot
  .github/workflows/chromatic.yml
Labels: ignore-for-release

#1681 va-on-this-page: Fix VoiceOver focus behavior
  packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
Labels: patch

#1698 CSS-Library: remove external link module
  packages/css-library/dist/img/exit-icon.png
  packages/css-library/dist/img/exit-icon.svg
  packages/css-library/dist/img/external-link-alt-hover.png
  packages/css-library/dist/img/external-link-alt-hover.svg
  packages/css-library/dist/img/external-link-alt.png
  packages/css-library/dist/img/external-link-alt.svg
  packages/css-library/dist/img/external-link-hover.png
  packages/css-library/dist/img/external-link-hover.svg
  packages/css-library/dist/img/external-link.png
  packages/css-library/dist/img/external-link.svg
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/utils.css.map
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/core/base.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/labels.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/modules/m-action-link.css.map
  packages/css-library/dist/stylesheets/modules/m-additional-info.css.map
  packages/css-library/dist/stylesheets/modules/m-alert.css.map
  packages/css-library/dist/stylesheets/modules/m-breadcrumbs.css.map
  packages/css-library/dist/stylesheets/modules/m-dropdown.css.map
  packages/css-library/dist/stylesheets/modules/m-emergency-banner.css.map
  packages/css-library/dist/stylesheets/modules/m-external-link.css
  packages/css-library/dist/stylesheets/modules/m-external-link.css.map
  packages/css-library/dist/stylesheets/modules/m-eyebrow.css.map
  packages/css-library/dist/stylesheets/modules/m-form-process.css.map
  packages/css-library/dist/stylesheets/modules/m-homepage-hero.css.map
  packages/css-library/dist/stylesheets/modules/m-hub-page-link-list.css.map
  packages/css-library/dist/stylesheets/modules/m-maintenance-banner.css.map
  packages/css-library/dist/stylesheets/modules/m-megamenu.css.map
  packages/css-library/dist/stylesheets/modules/m-modal.css.map
  packages/css-library/dist/stylesheets/modules/m-nav-sidebar.css.map
  packages/css-library/dist/stylesheets/modules/m-process-list.css.map
  packages/css-library/dist/stylesheets/modules/va-pagination.css.map
  packages/css-library/dist/stylesheets/modules/va-tabs.css.map
  packages/css-library/dist/stylesheets/shame.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/assets/img/exit-icon.png
  packages/css-library/src/assets/img/exit-icon.svg
  packages/css-library/src/assets/img/external-link-alt-hover.png
  packages/css-library/src/assets/img/external-link-alt-hover.svg
  packages/css-library/src/assets/img/external-link-alt.png
  packages/css-library/src/assets/img/external-link-alt.svg
  packages/css-library/src/assets/img/external-link-hover.png
  packages/css-library/src/assets/img/external-link-hover.svg
  packages/css-library/src/assets/img/external-link.png
  packages/css-library/src/assets/img/external-link.svg
  packages/css-library/src/stylesheets/core.scss
  packages/css-library/src/stylesheets/formation-overrides/elements/typography.scss
  packages/css-library/src/stylesheets/modules/m-external-link.scss
Labels: css-library

#1703 Web-Components, Core: Remove formation peer dependencies, update docs
  packages/core/README.md
  packages/core/package.json
  packages/integration-examples/vite-react-typescript/yarn.lock
  packages/storybook/package.json
  packages/web-components/package.json
  packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
  packages/web-components/src/components/va-file-input/va-file-input.tsx
  packages/web-components/src/index.html
  yarn.lock
Labels: minor

#1704 va-file-input: add file size limit to file contens preview generation
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1705 51.4.0 release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1685 `va-text-input` & `va-textarea`: Fix char count screen reader timing behavior
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
  packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
  packages/web-components/src/components/va-textarea/va-textarea.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
Labels: patch

#1710 [Metrics dashboard] Update weekly-reports.yml
  .github/workflows/weekly-reports.yml
Labels: ignore-for-release

#1706 core, web-components: upgrade react to v19
  packages/core/package.json
  packages/web-components/package.json
  yarn.lock
Labels: minor
