Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-02, with the labels that each got.

#1471 va-telephone | Remove aria-hidden from notClickable phone
  packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
  packages/web-components/src/components/va-telephone/va-telephone.tsx
Labels: patch

#1470 va-textarea: Move Headline location to be W3C compliant
  packages/web-components/src/components/va-textarea/va-textarea.scss
  packages/web-components/src/components/va-textarea/va-textarea.tsx
Labels: patch

#1477 va-radio-option: Fixes to global style bleeds
  packages/web-components/src/components/va-process-list/va-process-list-item.scss
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
Labels: patch

#1479 bump version numbers
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1480 va-radio-option: Hotfix to restore focus styles
  packages/web-components/src/components/va-radio-option/va-radio-option.scss
Labels: patch

#1481 bump versions
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1483 CSS-Library: Improved font handling for source sans pro across multiple platforms
  packages/css-library/dist/stylesheets/base/headings.css
  packages/css-library/dist/stylesheets/base/headings.css.map
  packages/css-library/dist/stylesheets/base/utils.css
  packages/css-library/dist/stylesheets/base/utils.css.map
  packages/css-library/dist/stylesheets/base/va.css.map
  packages/css-library/dist/stylesheets/core.css
  packages/css-library/dist/stylesheets/core.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/buttons.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/inputs.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/table.css.map
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css
  packages/css-library/dist/stylesheets/formation-overrides/elements/typography.css.map
  packages/css-library/dist/stylesheets/modules/m-emergency-banner.css
  packages/css-library/dist/stylesheets/modules/m-emergency-banner.css.map
  packages/css-library/dist/stylesheets/modules/m-maintenance-banner.css
  packages/css-library/dist/stylesheets/modules/m-maintenance-banner.css.map
  packages/css-library/dist/stylesheets/modules/m-megamenu.css
  packages/css-library/dist/stylesheets/modules/m-megamenu.css.map
  packages/css-library/dist/stylesheets/shame.css
  packages/css-library/dist/stylesheets/shame.css.map
  packages/css-library/dist/stylesheets/utilities.css
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/json/variables.json
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/tokens/fonts.json
Labels: css-library

#1462 Updated unauthenticated prefill alert, uneditable card components & usage example under Prefill pattern
  packages/storybook/stories/pattern-prefill/va-card.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefill-alert.stories.jsx
  packages/storybook/stories/pattern-prefill/va-prefilled-info-with-uneditable-card.stories.jsx
Labels: ignore-for-release

#1482 va-button-pair: add support for submitting form
  packages/storybook/.storybook/style.scss
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
Labels: patch

#1489 Update README.md for `Verdaccio` testing instructions
  README.md
Labels: documentation, ignore-for-release

#1484 va-language-toggle: Address accessibility issues
  packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
  packages/web-components/src/components/va-language-toggle/va-language-toggle.scss
  packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx
Labels: patch

#1491 PR Template: Remove zenhub reference
  .github/PULL_REQUEST_TEMPLATE.md
Labels: patch

#1485 va-button & va-button-pair: allow custom text for continue variation
  packages/storybook/stories/va-button-pair-uswds.stories.jsx
  packages/storybook/stories/va-button-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
  packages/web-components/src/components/va-button-pair/va-button-pair.tsx
  packages/web-components/src/components/va-button/test/va-button.e2e.ts
  packages/web-components/src/components/va-button/va-button.tsx
Labels: patch

#1488 va-banner: add dismissed-banner-id prop
  packages/storybook/stories/va-banner.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-banner/test/va-banner.spec.ts
  packages/web-components/src/components/va-banner/va-banner.tsx
Labels: minor

#1492 Check in the generated components file
  packages/web-components/src/components.d.ts
Labels: ignore-for-release

#1490 va-file-input: add support restricting the size of the file added
  packages/storybook/stories/va-file-input-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: minor

#1493 update package versions for release
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1486 va-table: Adds ability to arbitrarily right-align columns
  packages/storybook/stories/va-table-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/test/va-table.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table-inner/va-table-slot.css
  packages/web-components/src/components/va-table/va-table.tsx
Labels: minor

#1498 Update external link description
  packages/web-components/src/components/va-link/va-link.tsx
Labels: ignore-for-release

#1497 Add sign in alert no prefill variation
  packages/storybook/stories/va-alert-sign-in.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-alert-sign-in/AlertSignInVariants.ts
  packages/web-components/src/components/va-alert-sign-in/test/va-alert-sign-in.e2e.ts
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx
Labels: minor

#1495 Add a static files server script to Storybook for design.va.gov local development
  .gitignore
  packages/storybook/package.json
  yarn.lock
Labels: ignore-for-release

#1487 va-checkbox | Add internal description slot
  packages/storybook/stories/va-checkbox-uswds.stories.jsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
  packages/web-components/src/components/va-checkbox/va-checkbox.tsx
Labels: patch

#1478 va-combo-box: add option groups functionality
  packages/storybook/stories/va-combo-box-uswds.stories.jsx
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
  packages/web-components/src/components/va-combo-box/va-combo-box.scss
  packages/web-components/src/components/va-combo-box/va-combo-box.tsx
Labels: patch

#1501 va-table: Enabling stacked tables to always be full-width
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
Labels: patch

#1505 va-table-inner: patch to media query
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
Labels: ignore-for-release

#1504 update readme with steps to use Verdaccio in a GitHub Codespace
  README.md
Labels: ignore-for-release

#1506 Version Bumps for 2-26-25
  packages/core/package.json
  packages/css-library/package.json
  packages/web-components/package.json
  yarn.lock
Labels: ignore-for-release

#1503 CSS-Library: Addition of vads-c-eyebrow class
  packages/css-library/dist/stylesheets/modules/m-eyebrow.css
  packages/css-library/dist/stylesheets/modules/m-eyebrow.css.map
  packages/css-library/dist/tokens/css/variables.css
  packages/css-library/dist/tokens/scss/variables.scss
  packages/css-library/src/stylesheets/modules/m-eyebrow.scss
  packages/storybook/.storybook/style.scss
  packages/storybook/package.json
  packages/storybook/stories/Eyebrow.stories.mdx
  packages/storybook/stories/additional-docs.js
  yarn.lock
Labels: minor, css-library

#1507 Storybook: Dark mode support
  packages/storybook/.storybook/main.js
  packages/storybook/.storybook/preview.js
  packages/storybook/.storybook/style.scss
  packages/storybook/package.json
  yarn.lock
Labels: ignore-for-release

#1502 Adjust va-language-toggle font size and padding
  packages/web-components/src/components/va-language-toggle/va-language-toggle.scss
Labels: patch
