Repository department-of-veterans-affairs/component-library, pull requests merged in 2025-05, with the labels that each got.

#1587 va-modal: Fix TypeError on render
  packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
  packages/web-components/src/components/va-modal/va-modal.tsx
Labels: patch

#1586 va-additional-info: Fix TypeError on render
  packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
  packages/web-components/src/components/va-additional-info/va-additional-info.tsx
Labels: patch

#1588 va-checkbox: add normalized font size to description text
  packages/web-components/src/components/va-checkbox/va-checkbox.scss
Labels: patch

#1590 Remove release-please related files
  .github/workflows/release.yml
  .release-please-manifest.json
  release-please-config.json
Labels: ignore-for-release

#1589 Add icon filtering to storybook
  packages/storybook/stories/styles/va-icon.scss
  packages/storybook/stories/va-icon-uswds.stories.tsx
Labels: ignore-for-release

#1593 Add react-bindings build step to script
  setup.sh
Labels: ignore-for-release

#1594 Update readme.md
  packages/web-components/readme.md
Labels: ignore-for-release

#1596 Set va-modal visual to true by default in Storybook
  packages/storybook/stories/va-modal-uswds.stories.tsx
  packages/storybook/stories/wc-helpers.tsx
Labels: ignore-for-release

#1591 va-file-input: add aria-label to input for dictation
  packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
  packages/web-components/src/components/va-file-input/va-file-input.tsx
Labels: patch

#1597 Updating versions for release with patch bump v50.2.2
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1602 va-combo-box: make all options persist in dropdown after selection
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
Labels: patch

#1599 Update release steps
  README.md
Labels: ignore-for-release

#1600 va-text-input & va-statement-of-truth: add prop for adding Datadog privacy class on error message
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
  packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
  packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
  packages/web-components/src/components/va-text-input/va-text-input.tsx
Labels: minor

#1603 va-accordion: logic update to fix 2 clicks to collapse bug
  packages/web-components/src/components/va-accordion/va-accordion.tsx
Labels: patch

#1604 va-table: add data-sort-value attribute for raw number value sorting
  packages/storybook/stories/va-table-uswds.stories.tsx
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-table/sort/utils.tsx
  packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
  packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
  packages/web-components/src/components/va-table/va-table.tsx
Labels: minor

#1606 Setup script - Add react-component build to setup.sh
  .github/workflows/node.js.yml
  README.md
  setup.sh
Labels: ignore-for-release

#1608 Setup script - Add react-component build to setup.sh (#1606)
  .github/workflows/node.js.yml
  README.md
  setup.sh
Labels: ignore-for-release

#1605 va-combo-box: populate options when loading
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/va-combo-box.tsx
Labels: patch

#1595 va-input-telephone: add component
  packages/storybook/stories/va-input-telephone.stories.tsx
  packages/web-components/package.json
  packages/web-components/src/components.d.ts
  packages/web-components/src/components/va-combo-box/flags.scss
  packages/web-components/src/components/va-combo-box/flags.webp
  packages/web-components/src/components/va-combo-box/test/utils.spec.tsx
  packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
  packages/web-components/src/components/va-combo-box/utils.tsx
  packages/web-components/src/components/va-combo-box/va-combo-box-library.js
  packages/web-components/src/components/va-combo-box/va-combo-box.scss
  packages/web-components/src/components/va-combo-box/va-combo-box.tsx
  packages/web-components/src/components/va-input-telephone/test/utils.spec.tsx
  packages/web-components/src/components/va-input-telephone/test/va-input-telephone.e2e.ts
  packages/web-components/src/components/va-input-telephone/utils.tsx
  packages/web-components/src/components/va-input-telephone/va-input-telephone.scss
  packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx
  packages/web-components/src/utils/utils.spec.ts
  packages/web-components/src/utils/utils.ts
  yarn.lock
Labels: minor

#1611 va-search-filter: make headings consistent across breakpoints
  packages/web-components/src/components/va-search-filter/va-search-filter.scss
  packages/web-components/src/components/va-search-filter/va-search-filter.tsx
Labels: patch

#1613 va-alert-sign-in: replace straight apostrophes with curly ones
  packages/storybook/stories/va-alert-sign-in.stories.tsx
  packages/web-components/src/components/va-alert-sign-in/test/va-alert-sign-in.e2e.ts
  packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx
Labels: patch

#1615 Updating versions for release with patch bump v50.2.3
  packages/core/package.json
  packages/web-components/package.json
Labels: ignore-for-release

#1617 Storybook 8 migration
  packages/storybook/.storybook/main.ts
  packages/storybook/.storybook/manager.js
  packages/storybook/babel.config.json
  packages/storybook/package.json
  packages/storybook/stories/action-link.mdx
  packages/storybook/stories/action-link.stories.js
  packages/storybook/stories/action-link.stories.mdx
  packages/storybook/stories/how-to-use-storybook.mdx
  packages/storybook/stories/introduction.mdx
  packages/storybook/stories/sidenav.mdx
  packages/storybook/stories/sidenav.stories.js
  packages/storybook/stories/sidenav.stories.mdx
  packages/storybook/stories/tag.mdx
  packages/storybook/stories/tag.stories.js
  packages/storybook/stories/tag.stories.mdx
  yarn.lock
Labels: ignore-for-release
